"""Fixed product-owned setup for one ordinary Linux server agent.

This module deliberately owns one profile instead of exposing a deployment DSL.  It
composes the existing Approval, network/bootstrap, serve, status, guided-enrollment,
and activation surfaces while keeping host-specific writes bounded to AgentNet users,
private roots, environment files, and systemd units.
"""

from __future__ import annotations

import hashlib
import ipaddress
import grp
import json
import os
import pwd
import re
import shutil
import stat
import subprocess
import tempfile
import time
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Mapping
from urllib.parse import urlsplit

from pydantic import BaseModel, ConfigDict, Field, PrivateAttr, model_validator

from agentnet import __version__
from agentnet.approval.config import (
    ApprovalOwnerOIDCConfig,
    ApprovalServiceConfig,
    MANDATORY_APPROVAL_PURPOSES,
)
from agentnet.operations.config import (
    ApprovalServiceClientConfig,
    IndependentApproverConfig,
    OIDCEnrollmentConfig,
    OIDCTokenEndpointAuthMethod,
    RuntimeProfile,
    ScannerTrustConfig,
)
from agentnet.operations.config_migration import load_config_json
from agentnet.security.signatures import P256KeyPair, canonical_digest


CORE_USER = "agentnet"
APPROVAL_USER = "agentnet-approval"
CORE_UNIT = "agentnet-core.service"
APPROVAL_UNIT = "agentnet-approval.service"
CORE_DATA = Path("/var/lib/agentnet")
APPROVAL_DATA = Path("/var/lib/agentnet-approval")
CORE_CONFIG = CORE_DATA / "agentnet.json"
APPROVAL_CONFIG = APPROVAL_DATA / "config.json"
APPROVAL_STATE = APPROVAL_DATA / "state"
SETUP_MARKER = Path("/var/lib/agentnet-setup/setup.json")
CORE_ENV = Path("/etc/agentnet-secrets/core.env")
APPROVAL_ENV = Path("/etc/agentnet-secrets/approval.env")
CORE_PORT = 8080
APPROVAL_PORT = 8090
_ENV_NAME = re.compile(r"^[A-Z_][A-Z0-9_]{0,127}$")
_ENV_VALUE = re.compile(r"^[^\s'\"\\\x00-\x1f\x7f]+$")


class ServerSetupError(RuntimeError):
    """Fail-closed setup blocker safe to show in redacted operator evidence."""

    def __init__(self, blocker: str, message: str) -> None:
        super().__init__(message)
        self.blocker = blocker


class SetupOIDCProvider(BaseModel):
    """Provider fields only; Approval trust is generated by the product setup."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    issuer: str = Field(min_length=8, max_length=512)
    client_id: str = Field(min_length=1, max_length=512)
    redirect_uri: str = Field(min_length=8, max_length=2_048)
    audience: str | None = Field(default=None, min_length=1, max_length=512)
    token_endpoint_auth_method: OIDCTokenEndpointAuthMethod = OIDCTokenEndpointAuthMethod.NONE
    client_secret_env: str | None = Field(default=None, pattern=r"^[A-Z][A-Z0-9_]{2,127}$")
    allowed_endpoint_origins: tuple[str, ...] = Field(default=(), max_length=32)
    allowed_private_endpoint_cidrs: tuple[str, ...] = Field(default=(), max_length=64)
    pinned_endpoint_addresses: tuple[str, ...] = Field(default=(), max_length=128)
    allowed_signing_algorithms: tuple[Literal["RS256", "ES256"], ...] = ("RS256",)
    pinned_jwk_thumbprints: dict[str, str] = Field(default_factory=dict)
    binding_assurance: Literal["os_bound", "hardware_bound"] = "hardware_bound"

    @model_validator(mode="after")
    def provider_contract(self) -> "SetupOIDCProvider":
        confidential = self.token_endpoint_auth_method is not OIDCTokenEndpointAuthMethod.NONE
        if confidential != (self.client_secret_env is not None):
            raise ValueError("OIDC client-secret reference policy is inconsistent")
        try:
            issuer = urlsplit(self.issuer)
            issuer_port = issuer.port
        except ValueError as exc:
            raise ValueError("OIDC issuer is invalid") from exc
        if (
            issuer.scheme != "https"
            or not issuer.hostname
            or issuer.username is not None
            or issuer.password is not None
            or issuer.query
            or issuer.fragment
            or self.issuer.endswith("/")
            or issuer_port not in {None, 443}
        ):
            raise ValueError("OIDC issuer must be one canonical HTTPS issuer")
        return self


class SetupApprover(BaseModel):
    """Non-secret approver policy applied exactly during Approval provisioning."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    principal_id: str = Field(min_length=1, max_length=256)
    authority_kind: Literal["human", "guest"] = "human"
    domain_id: str = Field(pattern=r"^[a-z0-9][a-z0-9.-]{2,127}$")
    allowed_purposes: frozenset[str] = Field(min_length=1, max_length=32)
    oidc_issuer: str | None = Field(default=None, min_length=8, max_length=512)
    oidc_subject: str | None = Field(default=None, min_length=1, max_length=512)
    verified_email_alias: str | None = Field(default=None, min_length=3, max_length=320)

    @model_validator(mode="after")
    def exact_identity(self) -> "SetupApprover":
        identity_values = (self.oidc_issuer, self.oidc_subject, self.verified_email_alias)
        if any(value is not None for value in identity_values) and (
            self.oidc_issuer is None
            or (self.oidc_subject is None) == (self.verified_email_alias is None)
        ):
            raise ValueError("approver requires one exact OIDC subject or verified email alias")
        if self.verified_email_alias is not None:
            normalized = self.verified_email_alias.strip().casefold()
            try:
                normalized.encode("ascii")
            except UnicodeEncodeError as exc:
                raise ValueError("approver verified email alias must be normalized") from exc
            local, separator, domain = normalized.partition("@")
            if (
                separator != "@"
                or not local
                or not domain
                or "@" in domain
                or normalized != self.verified_email_alias
                or any(ord(character) <= 0x20 or ord(character) == 0x7F for character in normalized)
            ):
                raise ValueError("approver verified email alias must be normalized")
        if any(
            not purpose
            or len(purpose) > 256
            or purpose != purpose.strip()
            or any(ord(character) < 0x21 for character in purpose)
            for purpose in self.allowed_purposes
        ):
            raise ValueError("approver purpose is invalid")
        return self


class ServerSetupRequest(BaseModel):
    """Strict non-secret references for the fixed ordinary server-agent profile."""

    model_config = ConfigDict(extra="forbid", frozen=True, populate_by_name=True)
    _source_sha256: str = PrivateAttr(default="")

    schema_version: Literal["agentnet.server-setup.request.v1"] = Field(
        default="agentnet.server-setup.request.v1",
        alias="schema",
    )
    profile: Literal["always_on_server_agent"] = "always_on_server_agent"
    domain_id: str = Field(pattern=r"^[a-z0-9][a-z0-9.-]{2,127}$")
    service_audience: str = Field(min_length=8, max_length=512)
    runtime_instance_id: str = Field(min_length=1, max_length=128)
    core_public_origin: str = Field(min_length=8, max_length=2048)
    approval_public_origin: str = Field(min_length=8, max_length=2048)
    database_url: str = Field(min_length=16, max_length=2048)
    database_url_env: str = Field(default="AGENTNET_DATABASE_URL", pattern=r"^AGENTNET_[A-Z0-9_]{1,118}$")
    core_environment_file: Path
    approval_environment_file: Path
    oidc_provider_file: Path
    approval_owner_oidc_file: Path
    approval_approvers_file: Path
    scanner_trust_file: Path
    approval_approver_principal_id: str = Field(min_length=1, max_length=256)
    approval_verifier_id: str = Field(min_length=1, max_length=128)

    @staticmethod
    def _origin(value: str, *, label: str) -> str:
        try:
            parsed = urlsplit(value)
            port = parsed.port
        except ValueError as exc:
            raise ValueError(f"{label} is invalid") from exc
        if (
            parsed.scheme != "https"
            or not parsed.hostname
            or parsed.username is not None
            or parsed.password is not None
            or parsed.path not in {"", "/"}
            or parsed.query
            or parsed.fragment
        ):
            raise ValueError(f"{label} must be one exact HTTPS origin")
        hostname = parsed.hostname.lower()
        if hostname == "localhost" or hostname.endswith((".localhost", ".local")):
            raise ValueError(f"{label} must not use a local hostname")
        try:
            literal_address = ipaddress.ip_address(hostname)
        except ValueError:
            literal_address = None
        if literal_address is not None and not literal_address.is_global:
            raise ValueError(f"{label} must not use a non-public literal address")
        host = f"[{hostname}]" if ":" in hostname else hostname
        canonical = f"https://{host}"
        if port not in {None, 443}:
            canonical += f":{port}"
        if value.rstrip("/") != canonical:
            raise ValueError(f"{label} must use canonical spelling")
        return canonical

    @model_validator(mode="after")
    def fixed_profile(self) -> "ServerSetupRequest":
        self._origin(self.core_public_origin, label="Core public origin")
        self._origin(self.approval_public_origin, label="Approval public origin")
        expected_audience = f"urn:agentnet:{self.domain_id}:corporate-api"
        if self.service_audience != expected_audience:
            raise ValueError("service_audience must be the canonical domain audience")
        parsed_database = urlsplit(self.database_url)
        if (
            parsed_database.scheme not in {"postgresql", "postgres"}
            or not parsed_database.hostname
            or parsed_database.password is not None
            or parsed_database.query
            or parsed_database.fragment
        ):
            raise ValueError("database_url must be a password-free PostgreSQL DSN")
        for path in (
            self.core_environment_file,
            self.approval_environment_file,
            self.oidc_provider_file,
            self.approval_owner_oidc_file,
            self.approval_approvers_file,
            self.scanner_trust_file,
        ):
            if not path.is_absolute() or ".." in path.parts:
                raise ValueError("server setup input files must use absolute canonical paths")
        if self.core_public_origin == self.approval_public_origin:
            raise ValueError("Core and Approval require distinct public HTTPS origins")
        return self


@dataclass(frozen=True)
class SetupLayout:
    root: Path = Path("/")

    def host(self, path: Path) -> Path:
        if self.root == Path("/"):
            return path
        return self.root / path.relative_to("/")

    @property
    def lock(self) -> Path:
        return self.host(Path("/run/agentnet-setup/setup.lock"))

    @property
    def core_unit(self) -> Path:
        return self.host(Path("/etc/systemd/system") / CORE_UNIT)

    @property
    def approval_unit(self) -> Path:
        return self.host(Path("/etc/systemd/system") / APPROVAL_UNIT)


def _strict_json_bytes(raw: bytes, *, label: str) -> dict[str, Any]:
    try:
        value = json.loads(raw.decode("utf-8"), object_pairs_hook=_reject_duplicates)
    except (UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        raise ServerSetupError("invalid_input", f"{label} is invalid") from exc
    if not isinstance(value, dict):
        raise ServerSetupError("invalid_input", f"{label} must be one JSON object")
    return value


def _reject_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON key")
        result[key] = value
    return result


def _allowed_input_owners() -> set[int]:
    owners = {os.geteuid()}
    sudo_uid = os.environ.get("SUDO_UID")
    if sudo_uid and sudo_uid.isdecimal():
        owners.add(int(sudo_uid))
    return owners


def _read_private_input(path: Path, *, label: str, max_bytes: int = 1_048_576) -> bytes:
    try:
        canonical = path.resolve(strict=True)
    except OSError as exc:
        raise ServerSetupError("missing_input", f"{label} is unavailable") from exc
    if canonical != path or path.is_symlink() or path.parent.is_symlink():
        raise ServerSetupError("unsafe_input", f"{label} must be a canonical non-symlink file")
    try:
        descriptor = os.open(
            path,
            os.O_RDONLY
            | os.O_NONBLOCK
            | getattr(os, "O_NOFOLLOW", 0)
            | getattr(os, "O_CLOEXEC", 0),
        )
    except OSError as exc:
        raise ServerSetupError("missing_input", f"{label} is unavailable") from exc
    try:
        before = os.fstat(descriptor)
        if (
            not stat.S_ISREG(before.st_mode)
            or before.st_uid not in _allowed_input_owners()
            or before.st_nlink != 1
            or before.st_mode & 0o077
            or not 1 <= before.st_size <= max_bytes
        ):
            raise ServerSetupError("unsafe_input", f"{label} must be one bounded owner-only file")
        data = os.read(descriptor, before.st_size + 1)
        after = os.fstat(descriptor)
        if (
            len(data) != before.st_size
            or after.st_dev != before.st_dev
            or after.st_ino != before.st_ino
            or after.st_size != before.st_size
            or after.st_mtime_ns != before.st_mtime_ns
            or after.st_ctime_ns != before.st_ctime_ns
        ):
            raise ServerSetupError("unsafe_input", f"{label} changed while being read")
        return data
    finally:
        os.close(descriptor)


def load_server_setup_request(path: Path) -> ServerSetupRequest:
    try:
        canonical = path.absolute()
        raw = _read_private_input(canonical, label="setup request")
        request = ServerSetupRequest.model_validate(
            _strict_json_bytes(raw, label="setup request")
        )
        object.__setattr__(request, "_source_sha256", hashlib.sha256(raw).hexdigest())
        return request
    except ServerSetupError:
        raise
    except Exception as exc:
        raise ServerSetupError("invalid_request", "setup request is invalid") from exc


def _parse_environment(raw: bytes, *, label: str) -> dict[str, str]:
    result: dict[str, str] = {}
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ServerSetupError("invalid_environment", f"{label} is not UTF-8") from exc
    for number, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped != line or "=" not in line:
            raise ServerSetupError("invalid_environment", f"{label} line {number} is invalid")
        name, value = line.split("=", 1)
        if (
            not _ENV_NAME.fullmatch(name)
            or name in result
            or not _ENV_VALUE.fullmatch(value)
        ):
            raise ServerSetupError("invalid_environment", f"{label} line {number} is invalid")
        result[name] = value
    return result


def _parse_environment_file(path: Path, *, label: str) -> dict[str, str]:
    return _parse_environment(
        _read_private_input(path, label=label, max_bytes=262_144),
        label=label,
    )


_INPUT_FIELDS = (
    "core_environment_file",
    "approval_environment_file",
    "oidc_provider_file",
    "approval_owner_oidc_file",
    "approval_approvers_file",
    "scanner_trust_file",
)


def _read_input_bundle(request: ServerSetupRequest) -> dict[str, bytes]:
    public = request.model_dump(mode="json", by_alias=True)
    return {
        key: _read_private_input(
            Path(str(public[key])),
            label=f"{key} input",
            max_bytes=262_144 if key in {"core_environment_file", "approval_environment_file"} else 1_048_576,
        )
        for key in _INPUT_FIELDS
    }


def _request_digest(
    request: ServerSetupRequest,
    bundle: Mapping[str, bytes] | None = None,
) -> str:
    inputs = dict(bundle) if bundle is not None else _read_input_bundle(request)
    if not re.fullmatch(r"[a-f0-9]{64}", request._source_sha256):
        raise ServerSetupError("invalid_request", "setup request source binding is unavailable")
    public = request.model_dump(mode="json", by_alias=True)
    references: dict[str, dict[str, str]] = {}
    for key in _INPUT_FIELDS:
        path = Path(str(public[key]))
        raw = inputs[key]
        if key in {"core_environment_file", "approval_environment_file"}:
            names = sorted(_parse_environment(raw, label=f"{key} digest input"))
            fingerprint = canonical_digest({"environment_names": names})
        else:
            fingerprint = hashlib.sha256(raw).hexdigest()
        references[key] = {"path": str(path), "fingerprint": fingerprint}
    return canonical_digest(
        {
            "schema": "agentnet.server-setup.approval-digest.v1",
            "request_file_sha256": request._source_sha256,
            "referenced_inputs": references,
        }
    )


def _require_root_owned_executable(value: Path, *, label: str) -> Path:
    try:
        resolved = value.resolve(strict=True)
    except OSError as exc:
        raise ServerSetupError("missing_executable", f"installed {label} executable is unavailable") from exc
    if not resolved.is_file() or not os.access(resolved, os.X_OK):
        raise ServerSetupError("unsafe_executable", f"installed {label} executable is not executable")
    for item in (resolved, *resolved.parents):
        if item == Path("/"):
            break
        metadata = item.stat()
        if metadata.st_uid != 0:
            raise ServerSetupError(
                "unsafe_executable",
                f"installed {label} executable ownership is unsafe for server setup",
            )
        writable_by_others = bool(metadata.st_mode & 0o022)
        if writable_by_others:
            raise ServerSetupError(
                "unsafe_executable",
                f"installed {label} executable path is writable by another identity",
            )
        required = stat.S_IXOTH if item.is_dir() else stat.S_IROTH | stat.S_IXOTH
        if metadata.st_mode & required != required:
            raise ServerSetupError(
                "service_executable_inaccessible",
                f"installed {label} executable is not accessible to dedicated service identities",
            )
    return resolved


def _require_root_owned_tree(root: Path) -> Path:
    resolved = _require_root_owned_executable(root / "npm" / "bin" / "agentnet.mjs", label="agentnet")
    package_root = resolved.parents[2]
    if package_root != root.resolve(strict=True):
        raise ServerSetupError("unsafe_executable", "installed AgentNet package root is inconsistent")
    def walk_error(exc: OSError) -> None:
        raise ServerSetupError("unsafe_executable", "installed AgentNet package tree is not inspectable") from exc

    for directory, names, files in os.walk(
        package_root,
        followlinks=False,
        onerror=walk_error,
    ):
        directory_path = Path(directory)
        metadata = directory_path.lstat()
        if metadata.st_uid != 0 or metadata.st_mode & 0o022 or metadata.st_mode & 0o005 != 0o005:
            raise ServerSetupError("unsafe_executable", "installed AgentNet package tree custody is unsafe")
        for name in (*names, *files):
            item = directory_path / name
            item_metadata = item.lstat()
            required = 0o005 if stat.S_ISDIR(item_metadata.st_mode) else 0o004
            if (
                item.is_symlink()
                or item_metadata.st_uid != 0
                or item_metadata.st_mode & 0o022
                or item_metadata.st_mode & required != required
            ):
                raise ServerSetupError("unsafe_executable", "installed AgentNet package tree custody is unsafe")
    return resolved


def _resolve_host_tool(name: str) -> Path:
    located = shutil.which(name)
    if located is None:
        raise ServerSetupError("missing_host_tool", f"ordinary server setup requires {name}")
    return _require_root_owned_executable(Path(located), label=name)


def _resolve_uv_executable() -> Path:
    located = shutil.which("uv")
    if located is None:
        raise ServerSetupError("missing_executable", "installed uv executable is unavailable")
    return _require_root_owned_executable(Path(located), label="uv")


def _resolve_node_executable() -> Path:
    configured = os.environ.get("AGENTNET_NODE_EXECUTABLE")
    located = configured if configured and Path(configured).is_absolute() else shutil.which("node")
    if located is None:
        raise ServerSetupError("missing_executable", "installed Node.js executable is unavailable")
    return _require_root_owned_executable(Path(located), label="Node.js")


def _resolve_executable(node_executable: Path, uv_executable: Path) -> Path:
    package_root_value = os.environ.get("AGENTNET_PACKAGE_ROOT")
    if not package_root_value:
        raise ServerSetupError(
            "missing_package_provenance",
            "ordinary server setup requires the installed public AgentNet package launcher",
        )
    package_root = Path(package_root_value)
    if not package_root.is_absolute() or ".." in package_root.parts:
        raise ServerSetupError("unsafe_executable", "installed AgentNet package root is invalid")
    resolved = _require_root_owned_tree(package_root)
    runtime_root_value = os.environ.get("AGENTNET_NPM_RUNTIME_DIR")
    if not runtime_root_value:
        raise ServerSetupError(
            "missing_package_provenance",
            "ordinary server setup requires the installed package runtime binding",
        )
    runtime_root = Path(runtime_root_value)
    if not runtime_root.is_absolute() or ".." in runtime_root.parts:
        raise ServerSetupError("unsafe_executable", "installed package runtime binding is invalid")
    completed = subprocess.run(
        [str(node_executable), str(resolved), "--version"],
        env={
            "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "HOME": pwd.getpwuid(os.geteuid()).pw_dir,
            "LANG": "C.UTF-8",
            "AGENTNET_PACKAGE_ROOT": str(package_root),
            "AGENTNET_NODE_EXECUTABLE": str(node_executable),
            "AGENTNET_UV": str(uv_executable),
            "AGENTNET_NPM_RUNTIME_DIR": str(runtime_root),
            "UV_NO_MODIFY_PATH": "1",
        },
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        timeout=30,
        check=False,
    )
    if completed.returncode != 0 or completed.stdout.strip() != f"agentnet {__version__}":
        raise ServerSetupError("package_version", "installed agentnet executable version does not match package")
    return resolved


def _validate_inputs(
    request: ServerSetupRequest,
    bundle: Mapping[str, bytes] | None = None,
) -> tuple[SetupOIDCProvider, ApprovalOwnerOIDCConfig, tuple[SetupApprover, ...], ScannerTrustConfig]:
    inputs = dict(bundle) if bundle is not None else _read_input_bundle(request)
    try:
        oidc = SetupOIDCProvider.model_validate(
            _strict_json_bytes(inputs["oidc_provider_file"], label="Core OIDC provider input")
        )
        owner_oidc = ApprovalOwnerOIDCConfig.model_validate(
            _strict_json_bytes(inputs["approval_owner_oidc_file"], label="Approval owner OIDC input")
        )
    except ServerSetupError:
        raise
    except Exception as exc:
        raise ServerSetupError("invalid_oidc_input", "OIDC setup input is invalid") from exc
    try:
        scanner_trust = ScannerTrustConfig.model_validate(
            _strict_json_bytes(inputs["scanner_trust_file"], label="scanner trust input")
        )
    except ServerSetupError:
        raise
    except Exception as exc:
        raise ServerSetupError("invalid_scanner_trust", "scanner trust input is invalid") from exc
    approver_value = _strict_json_bytes(inputs["approval_approvers_file"], label="Approval approver input")
    entries = approver_value.get("approvers")
    if set(approver_value) != {"approvers"} or not isinstance(entries, list) or not entries:
        raise ServerSetupError("invalid_approvers", "Approval approver input is invalid")
    try:
        approvers = tuple(SetupApprover.model_validate(item) for item in entries)
    except Exception as exc:
        raise ServerSetupError("invalid_approvers", "Approval approver input is invalid") from exc
    if len({item.principal_id for item in approvers}) != len(approvers):
        raise ServerSetupError("invalid_approvers", "Approval approver principals must be unique")
    configured_issuers = {item.oidc_issuer for item in approvers if item.oidc_issuer is not None}
    if configured_issuers != {owner_oidc.issuer}:
        raise ServerSetupError("invalid_approvers", "Approval approvers do not match owner OIDC issuer")
    secret_references = {
        value
        for value in (oidc.client_secret_env, owner_oidc.client_secret_env)
        if value is not None
    }
    reserved_references = {
        "AGENTNET_NPM_RUNTIME_DIR",
        "AGENTNET_PACKAGE_ROOT",
        "AGENTNET_UV",
        "AGENTNET_NODE_EXECUTABLE",
    }
    if any(not value.startswith("AGENTNET_") for value in secret_references) or (
        secret_references & reserved_references
    ):
        raise ServerSetupError("invalid_secret_reference", "OIDC secret environment reference is unsafe")
    broker_reference = "AGENTNET_APPROVAL_CORE_TOKEN"
    credential_references = [
        request.database_url_env,
        broker_reference,
        *(value for value in (oidc.client_secret_env, owner_oidc.client_secret_env) if value is not None),
    ]
    if len(credential_references) != len(set(credential_references)):
        raise ServerSetupError(
            "invalid_secret_reference",
            "database, broker, and OIDC credentials require distinct environment references",
        )
    selected = [item for item in approvers if item.principal_id == request.approval_approver_principal_id]
    if len(selected) != 1:
        raise ServerSetupError("invalid_approvers", "selected Approval approver is unavailable")
    if not MANDATORY_APPROVAL_PURPOSES <= selected[0].allowed_purposes:
        raise ServerSetupError("invalid_approvers", "selected Approval approver lacks mandatory purposes")
    approval_host = urlsplit(request.approval_public_origin).hostname
    if oidc.redirect_uri != f"{request.core_public_origin}/v1/enrollment/oidc/callback":
        raise ServerSetupError("core_callback", "Core OIDC callback does not match public origin")
    if owner_oidc.redirect_uri != f"{request.approval_public_origin}/v1/approval/owner/oidc/callback":
        raise ServerSetupError("approval_callback", "Approval owner OIDC callback does not match public origin")
    if approval_host is None:
        raise ServerSetupError("approval_origin", "Approval public origin is invalid")
    probe_signer = P256KeyPair.generate()
    try:
        OIDCEnrollmentConfig(
            **oidc.model_dump(mode="python"),
            verifier_id=request.approval_verifier_id,
            trusted_approvers=(
                IndependentApproverConfig(
                    principal_id=selected[0].principal_id,
                    authority_kind=selected[0].authority_kind,
                    signer_key_id=probe_signer.thumbprint,
                    public_key_pem=probe_signer.public_pem,
                    allowed_purposes=selected[0].allowed_purposes,
                ),
            ),
            approval_service=ApprovalServiceClientConfig(
                origin=request.approval_public_origin,
                public_origin=request.approval_public_origin,
                service_credential_env="AGENTNET_APPROVAL_CORE_TOKEN",
                approver_principal_id=request.approval_approver_principal_id,
            ),
        )
    except Exception as exc:
        raise ServerSetupError("invalid_oidc_input", "Core OIDC provider input is invalid") from exc
    return oidc, owner_oidc, approvers, scanner_trust


def _validate_account(account: pwd.struct_passwd, name: str, home: Path) -> None:
    shells = {"/usr/sbin/nologin", "/sbin/nologin", "/bin/false"}
    try:
        primary_group = grp.getgrgid(account.pw_gid)
        effective_groups = set(os.getgrouplist(name, account.pw_gid))
        primary_peers = {
            candidate.pw_name
            for candidate in pwd.getpwall()
            if candidate.pw_gid == account.pw_gid
        }
    except (KeyError, OSError) as exc:
        raise ServerSetupError("identity_conflict", f"existing {name} account conflicts with fixed profile") from exc
    if (
        account.pw_uid == 0
        or account.pw_gid == 0
        or Path(account.pw_dir) != home
        or account.pw_shell not in shells
        or primary_group.gr_name != name
        or effective_groups != {account.pw_gid}
        or primary_peers != {name}
        or not set(primary_group.gr_mem) <= {name}
    ):
        raise ServerSetupError("identity_conflict", f"existing {name} account conflicts with fixed profile")


def _account_fact(name: str, home: Path) -> str:
    try:
        account = pwd.getpwnam(name)
    except KeyError:
        return "create"
    _validate_account(account, name, home)
    return "already_satisfied"


def _require_no_unit_overrides(layout: SetupLayout, unit: str) -> None:
    override_paths = (
        Path(f"/etc/systemd/system/{unit}.d"),
        Path(f"/run/systemd/system/{unit}.d"),
        Path(f"/etc/systemd/system.control/{unit}.d"),
        Path(f"/run/systemd/system.control/{unit}.d"),
        Path(f"/usr/local/lib/systemd/system/{unit}.d"),
        Path(f"/usr/lib/systemd/system/{unit}.d"),
        Path(f"/lib/systemd/system/{unit}.d"),
    )
    if any(layout.host(path).exists() or layout.host(path).is_symlink() for path in override_paths):
        raise ServerSetupError("unit_override_conflict", "managed AgentNet unit has unsupported overrides")


def _unit_arg(value: str) -> str:
    if any(character in value for character in "\n\r\x00"):
        raise ServerSetupError("unit_input", "systemd unit input contains a forbidden character")
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_units(
    node_executable: Path,
    executable: Path,
    uv_executable: Path,
) -> dict[str, bytes]:
    common = "\n".join(
        (
            "Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "UnsetEnvironment=NODE_OPTIONS NODE_PATH PYTHONPATH PYTHONHOME PYTHONSTARTUP UV_CONFIG_FILE UV_PROJECT UV_WORKING_DIR VIRTUAL_ENV",
            "NoNewPrivileges=true",
            "PrivateTmp=true",
            "PrivateDevices=true",
            "ProtectSystem=strict",
            "ProtectHome=true",
            "ProtectKernelTunables=true",
            "ProtectKernelModules=true",
            "ProtectControlGroups=true",
            "RestrictSUIDSGID=true",
            "CapabilityBoundingSet=",
            "AmbientCapabilities=",
            "SupplementaryGroups=",
            "UMask=0077",
            "LockPersonality=true",
            "RestrictRealtime=true",
            "SystemCallArchitectures=native",
        )
    )
    approval = f"""[Unit]
Description=AgentNet independent Approval service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={APPROVAL_USER}
Group={APPROVAL_USER}
EnvironmentFile={APPROVAL_ENV}
Environment=HOME={APPROVAL_DATA}
Environment=XDG_STATE_HOME={APPROVAL_DATA}/.local/state
Environment=XDG_CACHE_HOME={APPROVAL_DATA}/.cache
Environment=AGENTNET_NPM_RUNTIME_DIR={APPROVAL_DATA}/npm-runtime
Environment={_unit_arg(f"AGENTNET_UV={uv_executable}")}
ExecStart={_unit_arg(str(node_executable))} {_unit_arg(str(executable))} approval serve --config {_unit_arg(str(APPROVAL_CONFIG))} --host 127.0.0.1 --port {APPROVAL_PORT}
Restart=on-failure
RestartSec=2
{common}
ReadWritePaths={APPROVAL_DATA}

[Install]
WantedBy=multi-user.target
""".encode()
    core = f"""[Unit]
Description=AgentNet ordinary server agent
After=network-online.target {APPROVAL_UNIT}
Wants=network-online.target
Requires={APPROVAL_UNIT}

[Service]
Type=simple
User={CORE_USER}
Group={CORE_USER}
EnvironmentFile={CORE_ENV}
Environment=HOME={CORE_DATA}
Environment=XDG_STATE_HOME={CORE_DATA}/.local/state
Environment=XDG_CACHE_HOME={CORE_DATA}/.cache
Environment=AGENTNET_NPM_RUNTIME_DIR={CORE_DATA}/npm-runtime
Environment={_unit_arg(f"AGENTNET_UV={uv_executable}")}
ExecStart={_unit_arg(str(node_executable))} {_unit_arg(str(executable))} serve --config {_unit_arg(str(CORE_CONFIG))} --host 127.0.0.1 --port {CORE_PORT}
Restart=on-failure
RestartSec=2
{common}
ReadWritePaths={CORE_DATA}

[Install]
WantedBy=multi-user.target
""".encode()
    return {APPROVAL_UNIT: approval, CORE_UNIT: core}


def plan_server_setup(
    request: ServerSetupRequest,
    *,
    layout: SetupLayout = SetupLayout(),
) -> dict[str, Any]:
    if os.name != "posix" or not Path("/proc/1/comm").exists():
        raise ServerSetupError("unsupported_host", "ordinary server setup requires Linux with systemd")
    try:
        init_name = Path("/proc/1/comm").read_text(encoding="utf-8").strip()
    except OSError as exc:
        raise ServerSetupError("unsupported_host", "ordinary server setup cannot inspect init") from exc
    if init_name != "systemd" and layout.root == Path("/"):
        raise ServerSetupError("unsupported_host", "ordinary server setup requires systemd as PID 1")
    for tool in ("systemctl", "useradd"):
        _resolve_host_tool(tool)
    node_executable = _resolve_node_executable()
    uv_executable = _resolve_uv_executable()
    executable = _resolve_executable(node_executable, uv_executable)
    input_bundle = _read_input_bundle(request)
    oidc, owner_oidc, _approvers, _scanner_trust = _validate_inputs(request, input_bundle)
    core_environment = _parse_environment(input_bundle["core_environment_file"], label="Core environment input")
    approval_environment = _parse_environment(input_bundle["approval_environment_file"], label="Approval environment input")
    required_core = {request.database_url_env, "AGENTNET_APPROVAL_CORE_TOKEN"}
    if oidc.client_secret_env is not None:
        required_core.add(oidc.client_secret_env)
    required_approval = {"AGENTNET_APPROVAL_CORE_TOKEN"}
    if owner_oidc.client_secret_env is not None:
        required_approval.add(owner_oidc.client_secret_env)
    if not required_core <= set(core_environment) or not required_approval <= set(approval_environment):
        raise ServerSetupError("missing_secret_reference", "required runtime environment reference is absent")
    _service_environment(
        core_environment,
        CORE_DATA,
        uv_executable,
        allowed_names=frozenset(required_core),
    )
    _service_environment(
        approval_environment,
        APPROVAL_DATA,
        uv_executable,
        allowed_names=frozenset(required_approval),
    )
    if core_environment["AGENTNET_APPROVAL_CORE_TOKEN"] != approval_environment["AGENTNET_APPROVAL_CORE_TOKEN"]:
        raise ServerSetupError("broker_credential_mismatch", "Core and Approval broker credential references do not match")
    if core_environment[request.database_url_env] != request.database_url:
        raise ServerSetupError("database_reference_mismatch", "Core database reference does not match setup request")
    units = render_units(node_executable, executable, uv_executable)
    steps = [
        {"id": "preflight", "status": "completed"},
        {"id": "core_identity", "status": _account_fact(CORE_USER, CORE_DATA)},
        {"id": "approval_identity", "status": _account_fact(APPROVAL_USER, APPROVAL_DATA)},
        {"id": "private_roots", "status": "inspect_or_create"},
        {"id": "approval_provision", "status": "inspect_or_create"},
        {"id": "core_bootstrap", "status": "inspect_or_create"},
        {"id": "systemd_units", "status": "inspect_or_create"},
        {"id": "service_start", "status": "pending_explicit_apply_start"},
        {"id": "owner_ceremony", "status": "pending_human"},
    ]
    return {
        "schema": "agentnet.server-setup.evidence.v1",
        "status": "planned",
        "profile": request.profile,
        "request_digest": _request_digest(request, input_bundle),
        "package_version": __version__,
        "managed_units": sorted(units),
        "loopback_ports": {"core": CORE_PORT, "approval": APPROVAL_PORT},
        "https_topology": "external_self_hosted_reverse_proxy_to_loopback",
        "steps": steps,
        "authority_granted": False,
        "identity_enrolled": False,
        "production_durability_proven": False,
        "next": "freeze request_digest, then rerun with --expected-request-digest and --apply after one human approval",
    }


def _atomic_write(path: Path, payload: bytes, *, mode: int, uid: int = 0, gid: int = 0) -> str:
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    if path.parent.is_symlink():
        raise ServerSetupError("unsafe_path", "managed AgentNet path is a symlink")
    try:
        existing = os.open(
            path,
            os.O_RDONLY | os.O_NONBLOCK | getattr(os, "O_NOFOLLOW", 0),
        )
    except FileNotFoundError:
        existing = None
    except OSError as exc:
        raise ServerSetupError("managed_path_conflict", "managed AgentNet path conflicts with fixed profile") from exc
    if existing is not None:
        try:
            before = os.fstat(existing)
            if (
                not stat.S_ISREG(before.st_mode)
                or before.st_nlink != 1
                or before.st_size != len(payload)
                or stat.S_IMODE(before.st_mode) != mode
                or before.st_uid != uid
                or before.st_gid != gid
            ):
                raise ServerSetupError("managed_path_conflict", "managed AgentNet path conflicts with fixed profile")
            current = os.read(existing, len(payload) + 1)
            after = os.fstat(existing)
            if (
                current == payload
                and after.st_dev == before.st_dev
                and after.st_ino == before.st_ino
                and after.st_size == before.st_size
                and after.st_mtime_ns == before.st_mtime_ns
                and after.st_ctime_ns == before.st_ctime_ns
            ):
                return "already_satisfied"
            raise ServerSetupError("managed_path_conflict", "managed AgentNet path conflicts with fixed profile")
        finally:
            os.close(existing)
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, mode)
        os.fchown(descriptor, uid, gid)
        with os.fdopen(descriptor, "wb", closefd=True) as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        try:
            os.link(temporary, path, follow_symlinks=False)
        except FileExistsError as exc:
            raise ServerSetupError("managed_path_conflict", "managed AgentNet path conflicts with fixed profile") from exc
        temporary.unlink()
        directory = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    except BaseException:
        try:
            os.close(descriptor)
        except OSError:
            pass
        temporary.unlink(missing_ok=True)
        raise
    return "completed"


def _ensure_account(
    name: str,
    home: Path,
    *,
    useradd_executable: Path,
) -> pwd.struct_passwd:
    try:
        account = pwd.getpwnam(name)
    except KeyError:
        completed = subprocess.run(
            [
                str(useradd_executable),
                "--system",
                "--user-group",
                "--no-create-home",
                "--home-dir",
                str(home),
                "--shell",
                "/usr/sbin/nologin",
                name,
            ],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        if completed.returncode != 0:
            raise ServerSetupError("identity_create_failed", f"failed to create dedicated {name} identity")
        account = pwd.getpwnam(name)
    _account_fact(name, home)
    return account


def _ensure_root_private_directory(path: Path, *, uid: int, gid: int, label: str) -> str:
    if path.exists() or path.is_symlink():
        try:
            metadata = path.lstat()
        except OSError as exc:
            raise ServerSetupError(f"{label}_conflict", f"{label} root is unavailable") from exc
        if (
            not stat.S_ISDIR(metadata.st_mode)
            or metadata.st_uid != uid
            or metadata.st_gid != gid
            or stat.S_IMODE(metadata.st_mode) != 0o700
        ):
            raise ServerSetupError(f"{label}_conflict", f"{label} root conflicts with fixed profile")
        return "already_satisfied"
    path.mkdir(parents=True, mode=0o700)
    os.chown(path, uid, gid)
    os.chmod(path, 0o700)
    return "completed"


def _ensure_private_root(path: Path, account: pwd.struct_passwd) -> str:
    if path.exists():
        metadata = path.stat()
        if path.is_symlink() or not path.is_dir() or metadata.st_uid != account.pw_uid or metadata.st_gid != account.pw_gid or stat.S_IMODE(metadata.st_mode) != 0o700:
            raise ServerSetupError("private_root_conflict", "private AgentNet root conflicts with fixed profile")
        return "already_satisfied"
    path.mkdir(parents=True, mode=0o700)
    os.chown(path, account.pw_uid, account.pw_gid)
    os.chmod(path, 0o700)
    return "completed"


def _service_environment(
    base: Mapping[str, str],
    data: Path,
    uv_executable: Path,
    *,
    allowed_names: frozenset[str],
) -> dict[str, str]:
    reserved = {
        "PATH",
        "HOME",
        "XDG_STATE_HOME",
        "XDG_CACHE_HOME",
        "AGENTNET_NPM_RUNTIME_DIR",
        "AGENTNET_UV",
        "AGENTNET_PACKAGE_ROOT",
        "AGENTNET_NODE_EXECUTABLE",
    }
    supplied = set(base)
    if reserved & supplied:
        raise ServerSetupError("reserved_environment", "runtime environment overrides a setup-owned variable")
    if supplied != set(allowed_names):
        raise ServerSetupError("unexpected_environment", "runtime environment names do not match fixed request references")
    environment = {
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "HOME": str(data),
        "XDG_STATE_HOME": str(data / ".local/state"),
        "XDG_CACHE_HOME": str(data / ".cache"),
        "AGENTNET_NPM_RUNTIME_DIR": str(data / "npm-runtime"),
        "AGENTNET_UV": str(uv_executable),
    }
    environment.update(base)
    return environment


def _drop_identity(account: pwd.struct_passwd):
    def apply() -> None:
        os.setgroups([])
        os.setgid(account.pw_gid)
        os.setuid(account.pw_uid)
    return apply


def _run_as(
    account: pwd.struct_passwd,
    argv: list[str],
    *,
    environment: Mapping[str, str],
    allowed_returncodes: tuple[int, ...] = (0,),
) -> dict[str, Any]:
    completed = subprocess.run(
        argv,
        env=dict(environment),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
        preexec_fn=_drop_identity(account),
        text=True,
        timeout=300,
    )
    if completed.returncode not in allowed_returncodes:
        raise ServerSetupError("product_command_failed", "fixed setup product command failed")
    try:
        value = json.loads(completed.stdout)
    except json.JSONDecodeError as exc:
        raise ServerSetupError("invalid_product_evidence", "fixed setup product command returned invalid evidence") from exc
    if not isinstance(value, dict):
        raise ServerSetupError("invalid_product_evidence", "fixed setup product command returned invalid evidence")
    return value


def _require_private_file(path: Path, account: pwd.struct_passwd, *, blocker: str) -> None:
    try:
        metadata = path.lstat()
        resolved = path.resolve(strict=True)
    except OSError as exc:
        raise ServerSetupError(blocker, "managed private file is unavailable") from exc
    if (
        resolved != path
        or not stat.S_ISREG(metadata.st_mode)
        or metadata.st_nlink != 1
        or metadata.st_uid != account.pw_uid
        or metadata.st_gid != account.pw_gid
        or stat.S_IMODE(metadata.st_mode) != 0o600
    ):
        raise ServerSetupError(blocker, "managed private file custody conflicts with fixed profile")


def _read_private_managed_file(
    path: Path,
    account: pwd.struct_passwd,
    *,
    blocker: str,
    max_bytes: int,
) -> bytes:
    _require_private_file(path, account, blocker=blocker)
    try:
        descriptor = os.open(
            path,
            os.O_RDONLY
            | os.O_NONBLOCK
            | getattr(os, "O_NOFOLLOW", 0)
            | getattr(os, "O_CLOEXEC", 0),
        )
    except OSError as exc:
        raise ServerSetupError(blocker, "managed private file is unavailable") from exc
    try:
        before = os.fstat(descriptor)
        if (
            not stat.S_ISREG(before.st_mode)
            or before.st_nlink != 1
            or before.st_uid != account.pw_uid
            or before.st_gid != account.pw_gid
            or stat.S_IMODE(before.st_mode) != 0o600
            or not 1 <= before.st_size <= max_bytes
        ):
            raise ServerSetupError(blocker, "managed private file size or custody conflicts with fixed profile")
        payload = os.read(descriptor, before.st_size + 1)
        after = os.fstat(descriptor)
        current = path.lstat()
        if (
            len(payload) != before.st_size
            or after.st_dev != before.st_dev
            or after.st_ino != before.st_ino
            or after.st_size != before.st_size
            or after.st_mtime_ns != before.st_mtime_ns
            or after.st_ctime_ns != before.st_ctime_ns
            or current.st_dev != before.st_dev
            or current.st_ino != before.st_ino
        ):
            raise ServerSetupError(blocker, "managed private file changed while being read")
        return payload
    finally:
        os.close(descriptor)


def _require_private_directory(path: Path, account: pwd.struct_passwd, *, blocker: str) -> None:
    try:
        metadata = path.lstat()
        resolved = path.resolve(strict=True)
    except OSError as exc:
        raise ServerSetupError(blocker, "managed private directory is unavailable") from exc
    if (
        resolved != path
        or not stat.S_ISDIR(metadata.st_mode)
        or metadata.st_uid != account.pw_uid
        or metadata.st_gid != account.pw_gid
        or stat.S_IMODE(metadata.st_mode) != 0o700
    ):
        raise ServerSetupError(blocker, "managed private directory custody conflicts with fixed profile")


def _approval_trust(
    config_path: Path,
    account: pwd.struct_passwd,
    approval_state: Path,
) -> tuple[ApprovalServiceConfig, list[IndependentApproverConfig]]:
    _require_private_file(config_path, account, blocker="approval_config")
    _require_private_directory(approval_state, account, blocker="approval_custody")
    try:
        config = ApprovalServiceConfig.model_validate(
            json.loads(
                _read_private_managed_file(
                    config_path,
                    account,
                    blocker="approval_config",
                    max_bytes=1_048_576,
                ).decode("utf-8")
            )
        )
    except Exception as exc:
        raise ServerSetupError("approval_config", "Approval configuration is invalid") from exc
    expected_database = approval_state / "approval.sqlite3"
    expected_record_key = approval_state / "secrets" / "records.key"
    if (
        config.data_dir != approval_state
        or config.database_path != expected_database
        or config.record_key_path != expected_record_key
    ):
        raise ServerSetupError("approval_conflict", "existing Approval custody paths conflict with fixed request")
    _require_private_file(expected_record_key, account, blocker="approval_custody")
    _require_private_file(expected_database, account, blocker="approval_custody")
    trusted: list[IndependentApproverConfig] = []
    for index, item in enumerate(config.approvers, start=1):
        expected_signer = approval_state / "signers" / f"approver-{index}.pem"
        if item.signer_private_key_path != expected_signer:
            raise ServerSetupError("approval_custody", "Approval signer path conflicts with fixed profile")
        _require_private_file(expected_signer, account, blocker="approval_custody")
        try:
            signer = P256KeyPair.from_private_pem(
                _read_private_managed_file(
                    expected_signer,
                    account,
                    blocker="approval_custody",
                    max_bytes=65_536,
                )
            )
        except Exception as exc:
            raise ServerSetupError("approval_custody", "Approval signer custody is invalid") from exc
        if signer.thumbprint != item.signer_key_id:
            raise ServerSetupError("approval_custody", "Approval signer key identifier mismatch")
        trusted.append(
            IndependentApproverConfig(
                principal_id=item.principal_id,
                authority_kind=item.authority_kind,
                signer_key_id=item.signer_key_id,
                public_key_pem=signer.public_pem,
                allowed_purposes=item.allowed_purposes,
            )
        )
    return config, trusted


def _require_exact_approval_policy(
    config: ApprovalServiceConfig,
    *,
    request: ServerSetupRequest,
    owner_oidc: ApprovalOwnerOIDCConfig,
    approvers: tuple[SetupApprover, ...],
    approval_state: Path,
) -> None:
    actual_approvers = tuple(
        SetupApprover(
            principal_id=item.principal_id,
            authority_kind=item.authority_kind,
            domain_id=item.domain_id,
            allowed_purposes=item.allowed_purposes,
            oidc_issuer=item.oidc_issuer,
            oidc_subject=item.oidc_subject,
            verified_email_alias=item.verified_email_alias,
        )
        for item in config.approvers
    )
    approval_host = urlsplit(request.approval_public_origin).hostname
    if (
        approval_host is None
        or config.public_origin != request.approval_public_origin
        or config.rp_id != approval_host
        or config.verifier_id != request.approval_verifier_id
        or config.data_dir != approval_state
        or config.database_path != approval_state / "approval.sqlite3"
        or config.record_key_path != approval_state / "secrets" / "records.key"
        or config.internal_core_credential_env != "AGENTNET_APPROVAL_CORE_TOKEN"
        or config.owner_oidc != owner_oidc
        or actual_approvers != approvers
    ):
        raise ServerSetupError("approval_conflict", "existing Approval state conflicts with fixed request")


class _RejectRedirects(urllib.request.HTTPRedirectHandler):
    def redirect_request(self, req, fp, code, msg, headers, newurl):  # type: ignore[no-untyped-def]
        return None


def _health(url: str, *, expected: Mapping[str, object], attempts: int = 30) -> None:
    opener = urllib.request.build_opener(
        urllib.request.ProxyHandler({}),
        _RejectRedirects(),
    )
    for _ in range(attempts):
        try:
            with opener.open(url, timeout=2) as response:  # noqa: S310 - fixed validated setup URL
                payload = response.read(65_537)
                if response.status != 200 or len(payload) > 65_536:
                    raise ValueError("invalid health response")
                value = json.loads(payload)
                if isinstance(value, dict) and all(value.get(key) == item for key, item in expected.items()):
                    return
        except (urllib.error.URLError, TimeoutError, ValueError, json.JSONDecodeError):
            pass
        time.sleep(1)
    raise ServerSetupError("service_health", "AgentNet service did not return exact healthy identity evidence")


def apply_server_setup(
    request: ServerSetupRequest,
    *,
    start: bool,
    expected_request_digest: str,
    layout: SetupLayout = SetupLayout(),
    _allow_test_layout: bool = False,
) -> dict[str, Any]:
    plan = plan_server_setup(request, layout=layout)
    actual_digest = str(plan["request_digest"])
    if not re.fullmatch(r"[a-f0-9]{64}", expected_request_digest) or actual_digest != expected_request_digest:
        raise ServerSetupError(
            "approval_digest_mismatch",
            "current setup request does not match the frozen human-approved digest",
        )
    approved_digest = expected_request_digest
    if layout.root != Path("/") and not _allow_test_layout:
        raise ServerSetupError("test_layout", "apply requires the real host layout")
    if not _allow_test_layout and os.geteuid() != 0:
        raise ServerSetupError("privilege_required", "server setup apply requires root")
    try:
        import fcntl as posix_fcntl
    except ModuleNotFoundError as exc:
        raise ServerSetupError("unsupported_host", "ordinary server setup requires POSIX file locking") from exc
    root_uid = 0 if layout.root == Path("/") else os.geteuid()
    root_gid = 0 if layout.root == Path("/") else os.getegid()
    _ensure_root_private_directory(
        layout.lock.parent,
        uid=root_uid,
        gid=root_gid,
        label="setup_lock",
    )
    try:
        lock_descriptor = os.open(
            layout.lock,
            os.O_WRONLY
            | os.O_CREAT
            | os.O_NONBLOCK
            | getattr(os, "O_NOFOLLOW", 0)
            | getattr(os, "O_CLOEXEC", 0),
            0o600,
        )
    except OSError as exc:
        raise ServerSetupError("setup_lock", "AgentNet setup lock custody is unsafe") from exc
    lock_metadata = os.fstat(lock_descriptor)
    if (
        not stat.S_ISREG(lock_metadata.st_mode)
        or lock_metadata.st_nlink != 1
        or lock_metadata.st_uid != root_uid
        or lock_metadata.st_gid != root_gid
        or stat.S_IMODE(lock_metadata.st_mode) != 0o600
    ):
        os.close(lock_descriptor)
        raise ServerSetupError("setup_lock", "AgentNet setup lock custody conflicts with fixed profile")
    try:
        try:
            posix_fcntl.flock(lock_descriptor, posix_fcntl.LOCK_EX | posix_fcntl.LOCK_NB)
        except BlockingIOError as exc:
            raise ServerSetupError("setup_locked", "another AgentNet server setup is active") from exc
        core_data = layout.host(CORE_DATA)
        approval_data = layout.host(APPROVAL_DATA)
        core_config_path = layout.host(CORE_CONFIG)
        approval_config_path = layout.host(APPROVAL_CONFIG)
        approval_state = layout.host(APPROVAL_STATE)
        setup_marker = layout.host(SETUP_MARKER)
        core_env_path = layout.host(CORE_ENV)
        approval_env_path = layout.host(APPROVAL_ENV)

        node_executable = _resolve_node_executable()
        uv_executable = _resolve_uv_executable()
        executable = _resolve_executable(node_executable, uv_executable)
        systemctl_executable = _resolve_host_tool("systemctl")
        useradd_executable = _resolve_host_tool("useradd")
        input_bundle = _read_input_bundle(request)
        if _request_digest(request, input_bundle) != approved_digest:
            raise ServerSetupError("request_changed", "setup request inputs changed after approved preflight")
        oidc_provider, owner_oidc, approvers, scanner_trust = _validate_inputs(request, input_bundle)
        for unit in (APPROVAL_UNIT, CORE_UNIT):
            _require_no_unit_overrides(layout, unit)
        core_input = input_bundle["core_environment_file"]
        approval_input = input_bundle["approval_environment_file"]
        core_values = _parse_environment(core_input, label="Core environment input")
        approval_values = _parse_environment(approval_input, label="Approval environment input")
        core_account = _ensure_account(
            CORE_USER,
            CORE_DATA,
            useradd_executable=useradd_executable,
        )
        approval_account = _ensure_account(
            APPROVAL_USER,
            APPROVAL_DATA,
            useradd_executable=useradd_executable,
        )
        steps: list[dict[str, str]] = [
            {"id": "preflight", "status": "completed"},
            {"id": "core_identity", "status": "completed"},
            {"id": "approval_identity", "status": "completed"},
        ]
        steps.append({"id": "core_private_root", "status": _ensure_private_root(core_data, core_account)})
        steps.append({"id": "approval_private_root", "status": _ensure_private_root(approval_data, approval_account)})
        secret_root = layout.host(Path("/etc/agentnet-secrets"))
        steps.append(
            {
                "id": "secret_root",
                "status": _ensure_root_private_directory(
                    secret_root,
                    uid=root_uid,
                    gid=root_gid,
                    label="secret",
                ),
            }
        )
        steps.append(
            {
                "id": "setup_marker_root",
                "status": _ensure_root_private_directory(
                    setup_marker.parent,
                    uid=root_uid,
                    gid=root_gid,
                    label="setup_marker",
                ),
            }
        )
        steps.append({"id": "core_environment", "status": _atomic_write(core_env_path, core_input, mode=0o600, uid=root_uid, gid=root_gid)})
        steps.append({"id": "approval_environment", "status": _atomic_write(approval_env_path, approval_input, mode=0o600, uid=root_uid, gid=root_gid)})

        required_approval_environment = {"AGENTNET_APPROVAL_CORE_TOKEN"}
        if owner_oidc.client_secret_env is not None:
            required_approval_environment.add(owner_oidc.client_secret_env)
        approval_environment = _service_environment(
            approval_values,
            approval_data,
            uv_executable,
            allowed_names=frozenset(required_approval_environment),
        )
        approval_preexisting = approval_config_path.exists()
        if not approval_preexisting:
            staging_root = layout.host(Path("/run"))
            staging_root.mkdir(parents=True, exist_ok=True)
            staging = Path(tempfile.mkdtemp(prefix="agentnet-approval-setup-", dir=staging_root))
            os.chown(staging, approval_account.pw_uid, approval_account.pw_gid)
            os.chmod(staging, 0o700)
            try:
                approvers_copy = staging / "approvers.json"
                owner_oidc_copy = staging / "owner-oidc.json"
                _atomic_write(
                    approvers_copy,
                    input_bundle["approval_approvers_file"],
                    mode=0o600,
                    uid=approval_account.pw_uid,
                    gid=approval_account.pw_gid,
                )
                _atomic_write(
                    owner_oidc_copy,
                    input_bundle["approval_owner_oidc_file"],
                    mode=0o600,
                    uid=approval_account.pw_uid,
                    gid=approval_account.pw_gid,
                )
                result = _run_as(
                    approval_account,
                    [
                        str(node_executable), str(executable), "approval", "provision",
                        "--config", str(approval_config_path),
                        "--data-dir", str(approval_state),
                        "--public-origin", request.approval_public_origin,
                        "--rp-id", str(urlsplit(request.approval_public_origin).hostname),
                        "--verifier-id", request.approval_verifier_id,
                        "--approvers", str(approvers_copy),
                        "--owner-oidc-config", str(owner_oidc_copy),
                        "--internal-core-credential-env", "AGENTNET_APPROVAL_CORE_TOKEN",
                    ],
                    environment=approval_environment,
                )
                if result.get("schema") != "agentnet.approval.provision-result.v1":
                    raise ServerSetupError("approval_evidence", "Approval provision evidence schema is invalid")
                steps.append({"id": "approval_provision", "status": "completed"})
            finally:
                shutil.rmtree(staging, ignore_errors=True)
        else:
            _require_private_file(approval_config_path, approval_account, blocker="approval_config")

        approval_config, trusted = _approval_trust(
            approval_config_path,
            approval_account,
            approval_state,
        )
        _require_exact_approval_policy(
            approval_config,
            request=request,
            owner_oidc=owner_oidc,
            approvers=approvers,
            approval_state=approval_state,
        )
        if approval_preexisting:
            _run_as(
                approval_account,
                [str(node_executable), str(executable), "approval", "status", "--config", str(approval_config_path)],
                environment=approval_environment,
            )
            steps.append({"id": "approval_provision", "status": "already_satisfied"})
        selected = [item for item in trusted if item.principal_id == request.approval_approver_principal_id]
        if len(selected) != 1:
            raise ServerSetupError("approval_conflict", "selected Approval trust anchor is unavailable")
        oidc = OIDCEnrollmentConfig(
            **oidc_provider.model_dump(mode="python"),
            verifier_id=request.approval_verifier_id,
            trusted_approvers=tuple(trusted),
            approval_service=ApprovalServiceClientConfig(
                origin=request.approval_public_origin,
                public_origin=request.approval_public_origin,
                service_credential_env="AGENTNET_APPROVAL_CORE_TOKEN",
                approver_principal_id=request.approval_approver_principal_id,
            ),
        )
        oidc_path = core_data / "oidc-enrollment.json"
        oidc_payload = json.dumps(oidc.model_dump(mode="json"), indent=2, sort_keys=True).encode() + b"\n"
        steps.append({"id": "core_oidc_config", "status": _atomic_write(oidc_path, oidc_payload, mode=0o600, uid=core_account.pw_uid, gid=core_account.pw_gid)})
        scanner_path = core_data / "scanner-trust.json"
        scanner_payload = json.dumps(scanner_trust.model_dump(mode="json"), indent=2, sort_keys=True).encode() + b"\n"
        steps.append({"id": "scanner_trust", "status": _atomic_write(scanner_path, scanner_payload, mode=0o600, uid=core_account.pw_uid, gid=core_account.pw_gid)})

        required_core_environment = {
            request.database_url_env,
            "AGENTNET_APPROVAL_CORE_TOKEN",
        }
        if oidc_provider.client_secret_env is not None:
            required_core_environment.add(oidc_provider.client_secret_env)
        core_environment = _service_environment(
            core_values,
            core_data,
            uv_executable,
            allowed_names=frozenset(required_core_environment),
        )
        core_preexisting = core_config_path.exists()
        if not core_preexisting:
            result = _run_as(
                core_account,
                [
                    str(node_executable), str(executable), "network", "create",
                    "--config", str(core_config_path),
                    "--data-dir", str(core_data / "core"),
                    "--domain", request.domain_id,
                    "--database-url-env", request.database_url_env,
                    "--database-url-from-env",
                    "--public-base-url", request.core_public_origin,
                    "--oidc-config", str(oidc_path),
                    "--scanner-trust-config", str(scanner_path),
                    "--runtime-instance-id", request.runtime_instance_id,
                ],
                environment=core_environment,
                allowed_returncodes=(0, 1),
            )
            readiness = result.get("local_readiness")
            _require_private_file(core_config_path, core_account, blocker="core_custody")
            if (
                result.get("config") != str(core_config_path)
                or not isinstance(readiness, dict)
                or not isinstance(readiness.get("storage"), dict)
                or not readiness["storage"].get("ready")
                or not isinstance(readiness.get("audit"), dict)
                or not readiness["audit"].get("valid")
            ):
                raise ServerSetupError("core_evidence", "Core bootstrap evidence is invalid")
            bootstrap_status = "completed"
        else:
            _require_private_file(core_config_path, core_account, blocker="core_custody")
            bootstrap_status = "already_satisfied"

        config = load_config_json(
            _read_private_managed_file(
                core_config_path,
                core_account,
                blocker="core_custody",
                max_bytes=1_048_576,
            ).decode("utf-8")
        )
        identity_enrolled = bool(config.enrolled_harness_id and config.enrolled_credential_id)
        if (
            config.profile is not RuntimeProfile.ALWAYS_ON_SERVER_AGENT
            or config.domain_id != request.domain_id
            or config.data_dir != core_data / "core"
            or config.database_url != request.database_url
            or config.database_url_env != request.database_url_env
            or config.artifact_backend != "postgres-manifest"
            or config.artifact_dir != core_data / "core" / "artifacts"
            or config.public_base_url != request.core_public_origin
            or config.effective_service_audience != request.service_audience
            or config.runtime_instance_id != request.runtime_instance_id
            or config.oidc_enrollment != oidc
            or config.scanner_trust != scanner_trust
            or config.a2a is not None
            or config.local_bindings is not None
            or config.relay is not None
            or config.federation_trust is not None
            or config.postgres_recovery_topology
        ):
            raise ServerSetupError("core_conflict", "existing Core state conflicts with fixed request")
        if core_preexisting:
            _run_as(
                core_account,
                [str(node_executable), str(executable), "bootstrap-server-agent", "--config", str(core_config_path)],
                environment=core_environment,
            )
        steps.append({"id": "core_bootstrap", "status": bootstrap_status})

        marker = {
            "schema": "agentnet.server-setup.marker.v1",
            "request_digest": approved_digest,
            "approval_config_digest": canonical_digest(approval_config.model_dump(mode="json")),
            "core_config_digest": canonical_digest(
                config.model_dump(
                    mode="json",
                    exclude={"enrolled_harness_id", "enrolled_credential_id"},
                )
            ),
            "units": [APPROVAL_UNIT, CORE_UNIT],
        }
        steps.append({"id": "setup_marker", "status": _atomic_write(setup_marker, json.dumps(marker, sort_keys=True).encode() + b"\n", mode=0o600, uid=root_uid, gid=root_gid)})

        for unit, payload in render_units(node_executable, executable, uv_executable).items():
            target = layout.host(Path("/etc/systemd/system") / unit)
            steps.append({"id": f"unit:{unit}", "status": _atomic_write(target, payload, mode=0o644, uid=root_uid, gid=root_gid)})
        if start:
            for argv in (
                [str(systemctl_executable), "daemon-reload"],
                [str(systemctl_executable), "enable", "--now", APPROVAL_UNIT],
                [str(systemctl_executable), "enable", CORE_UNIT],
                [str(systemctl_executable), "restart", CORE_UNIT],
            ):
                completed = subprocess.run(argv, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
                if completed.returncode != 0:
                    raise ServerSetupError("systemd_start", "failed to start AgentNet managed units")
            for unit in (APPROVAL_UNIT, CORE_UNIT):
                active = subprocess.run(
                    [str(systemctl_executable), "is-active", "--quiet", unit],
                    stdin=subprocess.DEVNULL,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    check=False,
                )
                if active.returncode != 0:
                    raise ServerSetupError("systemd_start", "AgentNet managed unit is not active")
            approval_health = {
                "schema": "agentnet.approval.health.v1",
                "service": "agentnet-approval",
                "version": __version__,
                "status": "alive",
                "public_origin": request.approval_public_origin,
                "verifier_id": request.approval_verifier_id,
            }
            core_health = {
                "schema": "agentnet.core.health.v1",
                "service": "agentnet-core",
                "version": __version__,
                "status": "alive",
                "profile": request.profile,
                "domain_id": request.domain_id,
                "public_origin": request.core_public_origin,
                "service_audience": request.service_audience,
                "runtime_instance_id": request.runtime_instance_id,
            }
            _health(f"http://127.0.0.1:{APPROVAL_PORT}/healthz", expected=approval_health)
            _health(f"http://127.0.0.1:{CORE_PORT}/healthz", expected=core_health)
            _health(f"{request.approval_public_origin}/healthz", expected=approval_health)
            _health(f"{request.core_public_origin}/healthz", expected=core_health)
            steps.append({"id": "service_start", "status": "completed"})
            steps.append({"id": "public_https_routes", "status": "completed"})
            if identity_enrolled:
                readiness = {
                    "schema": "agentnet.core.readiness.v1",
                    "service": "agentnet-core",
                    "version": __version__,
                    "ready": True,
                    "profile": request.profile,
                    "domain_id": request.domain_id,
                    "public_origin": request.core_public_origin,
                    "service_audience": request.service_audience,
                    "runtime_instance_id": request.runtime_instance_id,
                    "deployment_binding": {"ready": True, "required": True},
                }
                _health(f"http://127.0.0.1:{CORE_PORT}/readyz", expected=readiness)
                _health(f"{request.core_public_origin}/readyz", expected=readiness)
                steps.append({"id": "operational_readiness", "status": "completed"})
                status = "operational"
                next_action = "enroll additional ordinary laptops with agentnet join guided"
            else:
                status = "waiting_owner_oidc_or_passkey"
                next_action = "complete owner passkey registration and guided identity-only enrollment"
        else:
            steps.append({"id": "service_start", "status": "pending_explicit_start"})
            status = "configured_not_started"
            next_action = "rerun with the same --expected-request-digest plus --apply --start inside the approved scope"
        return {
            **plan,
            "status": status,
            "steps": steps,
            "next": next_action,
            "authority_granted": False,
            "identity_enrolled": identity_enrolled,
            "production_durability_proven": False,
        }
    finally:
        os.close(lock_descriptor)


__all__ = [
    "APPROVAL_PORT",
    "CORE_PORT",
    "ServerSetupError",
    "ServerSetupRequest",
    "SetupLayout",
    "apply_server_setup",
    "load_server_setup_request",
    "plan_server_setup",
    "render_units",
]
