// Code generated by internal/ui/tsgen_test.go from the page API's Go types. DO NOT EDIT.
// Regenerate: go test ./internal/ui -run TestTypeScriptViewTypes -update

export interface Action {
  send_id?: string;
  do: string;
  id?: string;
  body?: string;
  reason?: string;
  ids?: string[];
  key?: string;
}

export interface AgentAsk {
  topic?: string;
  id?: string;
  reply_receiver?: ReplyReceiverSelection;
  pid: string;
  kind: string;
  body: string;
  files?: string[];
}

export interface AgentCatalogChange {
  action: string;
  id?: string;
  label?: string;
  harness?: string;
  dir?: string;
}

export interface AgentCatalogChangeResult {
  saved: boolean;
  published: boolean;
  agent?: CatalogAgent;
  note: string;
}

export interface AgentCatalogView {
  host: string;
  local: boolean;
  agents: CatalogAgent[] | null;
  harnesses?: HarnessView[];
}

export interface AgentInDM {
  conv: string;
  pid: string;
  state: string;
}

export interface AgentInvite {
  agent_id?: string;
  conv: string;
  host: string;
  share: string[] | null;
  tasks_from: string[] | null;
  note: string;
}

export interface AgentLink {
  agent_id?: string;
  address: string;
  dms: AgentInDM[] | null;
}

export interface AgentRecord {
  v: number;
  id: string;
  host: string;
  host_key: string;
  label: string;
  ts: number;
  sig?: string;
}

export interface AgentView {
  pids?: string[];
  member?: boolean;
  inviters?: PersonView[];
  external?: boolean;
  agent_id?: string;
  pid: string;
  state: string;
  state_text: string;
  host: PersonView;
  host_here: boolean;
  inviter: PersonView;
  note?: string;
  shared: string[] | null;
  missing: number;
  tasks_from: PersonView[] | null;
  held: number;
  invited: string;
  can_decide: boolean;
  can_dismiss: boolean;
  can_ask: boolean;
}

export interface ApprovalRevoke {
  person?: string;
  kind: string;
  address?: string;
  pid?: string;
}

export interface ApprovalsView {
  questions: QuestionApproval[] | null;
  tasks: TaskGrantView[] | null;
  participations: ParticipationGrant[] | null;
  read_only: boolean;
  unresolved?: string[];
}

export interface AssistantSetupHarness {
  id: string;
  label: string;
  detected: boolean;
  configured: boolean;
  registered: boolean;
  supported: boolean;
  state: string;
  note: string;
  change?: string;
  next?: string;
  target?: string;
}

export interface AssistantSetupRequest {
  action?: string;
  harnesses?: string[];
  review_id?: string;
}

export interface AssistantSetupView {
  local: boolean;
  harnesses: AssistantSetupHarness[] | null;
  review_id?: string;
  note?: string;
}

export interface Author {
  label: string;
  about: string;
}

export interface BlobStorageUsage {
  stored: StorageBucket;
  incomplete: StorageBucket;
}

export interface CatalogAgent {
  record: AgentRecord;
  enabled: boolean;
  responder?: ResponderView;
}

export interface ControlAction {
  conv?: string;
  id: string;
  dir: string;
  emoji?: string;
  remove?: boolean;
  text?: string;
}

export interface ConvItem {
  reason: string;
  conv: string;
  pid?: string;
  id?: string;
  peer: string;
  kind?: string;
  why: string;
  excerpt: string;
  at: string;
  unread?: boolean;
  actions?: string[];
  decide_on?: string;
}

export interface CopyView {
  own?: boolean;
  person?: string;
  to: string;
  state: string;
  detail?: string;
}

export interface DMDraft {
  topic?: string;
  id?: string;
  pid?: string;
  reply_receiver?: ReplyReceiverSelection;
  conv: string;
  body: string;
  reply_to?: string;
  files?: string[];
  quote?: string;
}

export interface DMMessage {
  topic?: string;
  topic_event?: TopicEvent;
  agent_author_pid?: string;
  group_ref?: GroupHistoryRef;
  excerpt_pid?: string;
  claimed_key?: string;
  target?: Target;
  agent_id?: string;
  id: string;
  lid?: string;
  dir: string;
  from: string;
  kind: string;
  body: string;
  reply_to?: string;
  origin?: string;
  state: string;
  state_text: string;
  detail?: string;
  at: string;
  unread?: boolean;
  replica?: boolean;
  pid?: string;
  attachments?: FileView[];
  verified_agent: boolean;
  via?: string;
  copies?: CopyView[];
  synced_from?: string;
  to?: string;
  event?: string;
  reactions?: ReactionView[];
  edited?: boolean;
  revision?: number;
  text?: string;
  deleted?: boolean;
  can?: string[];
  exec?: ExecView;
  actions?: string[];
  job_detail?: string;
  event_type?: string;
  event_by?: string;
  quote?: string;
  sent_at?: string;
  delivery?: string;
}

export interface DMSummary {
  kind?: string;
  members?: GroupMemberView[];
  frozen?: string;
  role?: string;
  id: string;
  peer: PersonView;
  created: string;
  mine: boolean;
  count: number;
  title: string;
  last: string;
  last_at: string;
  unread: number;
  held: number;
  waiting: number;
  guests: number;
  decide: number;
  last_event?: LastEvent;
}

export interface DMThread {
  topics?: ThreadSummary[];
  kind?: string;
  title?: string;
  members?: GroupMemberView[];
  role?: string;
  id: string;
  peer: PersonView;
  created: string;
  mine: boolean;
  frozen?: string;
  messages: DMMessage[] | null;
  agents: AgentView[] | null;
  guests?: GuestView[];
  audience_pending?: boolean;
}

export interface Decider {
  person?: string;
  label?: string;
  address?: string;
}

export interface DecisionAction {
  host: string;
  id: string;
  key: string;
  action: string;
  expect: string;
  attempt: number;
  text?: string;
  report: string;
}

export interface DecisionResult {
  decision: string;
  state: string;
  refused?: string;
  at: number;
}

export interface DeleteConversationAction {
  conv?: string;
  peer?: string;
  thread?: string;
}

export interface DeviceLink {
  url: string;
  expires: string;
  app_url?: string;
}

export interface DeviceView {
  address: string;
  name: string;
  fingerprint: string;
  this?: boolean;
  human?: boolean;
}

export interface DirMember {
  address: string;
  presence: string;
  joined: string;
}

export interface Directory {
  status: string;
  current: boolean;
  at?: string;
  truncated: boolean;
  members: DirMember[] | null;
}

export interface Draft {
  id?: string;
  reply_receiver?: ReplyReceiverSelection;
  agent_id?: string;
  to: string;
  kind: string;
  body: string;
  reply_to?: string;
  files?: string[];
  quote?: string;
}

export interface ExecView {
  state: string;
  at: number;
  detail?: string;
  host: string;
  attempt?: number;
  stale?: boolean;
}

export interface File {
  name: string;
  size: number;
  saved?: string;
  index: number;
  openable: boolean;
  note?: string;
}

export interface FileLimits {
  max_file: number;
  max_message?: number;
  max_count: number;
}

export interface FileView {
  index: number;
  name: string;
  size: number;
  saved?: string;
  availability?: string;
  note?: string;
  openable: boolean;
}

export interface FolderView {
  name: string;
  path: string;
}

export interface FoldersView {
  path: string;
  parent?: string;
  home: string;
  roots?: string[];
  dirs: FolderView[] | null;
  truncated?: boolean;
}

export interface GetAppPlatform {
  id: string;
  label: string;
  url: string;
}

export interface GetAppView {
  version: string;
  detected?: string;
  platforms: GetAppPlatform[] | null;
}

export interface GoogleAccess {
  workspace_url: string;
  enabled: boolean;
  can_admin: boolean;
  emails: GoogleEmail[] | null;
  domains: string[] | null;
}

export interface GoogleAccessChange {
  email?: string;
  domain?: string;
  remove: boolean;
  admin?: boolean;
}

export interface GoogleEmail {
  domain_member: boolean;
  email: string;
  admin: boolean;
  denied: boolean;
}

export interface GroupChange {
  conv: string;
  action: string;
  title?: string;
  person?: string;
}

export interface GroupChangeResult {
  queued: boolean;
}

export interface GroupHistoryRef {
  lid: string;
  author: string;
  hash: string;
}

export interface GroupInvitationView {
  id: string;
  conv: string;
  direction: string;
  status: string;
  title: string;
  inviter: string;
  target: string;
  history: GroupHistoryRef[] | null;
}

export interface GroupInviteDraft {
  conv: string;
  person: string;
  history: { last?: number; since?: number; refs?: GroupHistoryRef[]; };
}

export interface GroupMemberView {
  person?: string;
  label: string;
  email?: string;
  address: string;
  fingerprint?: string;
  state: string;
  published?: boolean;
  agents?: AgentLink[];
  devices?: DeviceView[];
  admin: boolean;
}

export interface GuestAction {
  conv?: string;
  host?: string;
  share?: string[];
  note?: string;
  pid?: string;
  accept?: boolean;
}

export interface GuestCheck {
  ready: boolean;
  needs_update: GuestCheckPerson[] | null;
  offline: string[] | null;
  text: string;
}

export interface GuestCheckPerson {
  label: string;
  me: boolean;
  role: string;
}

export interface GuestCheckRequest {
  conv: string;
  host: string;
}

export interface GuestView {
  needs_update?: string[];
  pid: string;
  state: string;
  state_text: string;
  host: PersonView;
  host_here: boolean;
  inviter: PersonView;
  shared: string[] | null;
  missing: number;
  held: number;
  can_decide: boolean;
  can_leave: boolean;
  can_end: boolean;
  can_send: boolean;
  audience_pending: boolean;
}

export interface HarnessView {
  name: string;
  found: boolean;
  path?: string;
  tested_live?: string;
  question_mode?: string;
}

export interface HistoryCopy {
  device: string;
  name: string;
  done: number;
  total: number;
  state: string;
}

export interface HubStorage {
  scope: string;
  quota_scope: string;
  own: BlobStorageUsage;
  global?: BlobStorageUsage;
  quota_bytes: number;
  max_file_bytes: number;
  upload_idle_ttl_seconds: number;
  location: string;
  policy: HubStoragePolicy;
}

export interface HubStoragePolicy {
  delivered_attachments: string;
  unattached_attachments: string;
  undelivered_attachments: string;
  message_envelopes: string;
  incomplete_uploads: string;
  manual_delivered_age_default_seconds: number;
  manual_unattached_age_default_seconds: number;
}

export interface InviteRequest {
  name: string;
  admin: boolean;
  days: number;
}

export interface InviteView {
  link: string;
  label: string;
  expires: string;
  message: string;
}

export interface InvitesView {
  can_invite: boolean;
  invites: PendingInviteView[] | null;
}

export interface LastEvent {
  kind: string;
  pid: string;
  by: string;
}

export interface LinkRequest {
  id: string;
  address: string;
  name: string;
  fingerprint: string;
  requested_at: string;
  expires: string;
  state: string;
}

export interface LinkState {
  state: string;
  detail?: string;
}

export interface LocalStorage {
  scope: string;
  location: string;
  areas: StorageArea[] | null;
  known: StorageAmount;
  complete: boolean;
  exclusions: string;
}

export interface ManagedReplyHandoff {
  agent_id: string;
  instructions: string;
  mode: string;
}

export interface Me {
  address: string;
  fingerprint: string;
  responder: string;
  responder_dir: string;
  agent: boolean;
}

export interface Message {
  target?: Target;
  agent_id?: string;
  id: string;
  dir: string;
  from: string;
  to: string;
  kind: string;
  body: string;
  reply_to?: string;
  at: string;
  state?: string;
  status?: string;
  path?: string;
  responder?: string;
  summary?: string;
  detail?: string;
  unread?: boolean;
  files?: File[];
  author: Author;
  state_text?: string;
  next?: string;
  actions?: string[];
  reactions?: ReactionView[];
  edited?: boolean;
  revision?: number;
  text?: string;
  deleted?: boolean;
  can?: string[];
  exec?: ExecView;
  quote?: string;
  sent_at?: string;
  proposal?: ProposalView;
}

export interface NotifyView {
  available: boolean;
  native: boolean;
  enabled: boolean;
  pending: boolean;
  reason?: string;
  mutes: string[] | null;
  allowed: string[] | null;
}

export interface Overview {
  groups: boolean;
  group_invitations?: GroupInvitationView[];
  reply_receivers: boolean;
  reply_sessions: boolean;
  demo: boolean;
  app?: boolean;
  me: Me;
  threads: ThreadSummary[] | null;
  topics?: PeerTopics[];
  topic_list: boolean;
  review: ReviewItem[] | null;
  quarantine: QuarantineItem[] | null;
  release?: string;
  seq: number;
  version: string;
  directory: Directory;
  needs_you: ConvItem[] | null;
  held: ConvItem[] | null;
  persons: boolean;
  agents: boolean;
  notify?: NotifyView;
  reminders?: ReminderView[];
  remind: boolean;
  files?: FileLimits;
  person?: PersonView;
  people: PersonView[] | null;
  dms: DMSummary[] | null;
  role?: string;
  link?: LinkState;
  links?: LinkRequest[];
  history?: HistoryCopy[];
  workspace?: WorkspaceView;
  agent_devices: string[] | null;
}

export interface ParticipationGrant {
  conv: string;
  pid: string;
  agent_id?: string;
  keys: string[] | null;
  tasks_from: PersonView[] | null;
  external?: boolean;
}

export interface PeerKey {
  pinned?: string;
  pending?: string;
}

export interface PeerTopics {
  peer: string;
  total: number;
  archived: number;
  archived_unread: number;
  latest: ThreadSummary;
}

export interface PendingInviteView {
  id: string;
  name: string;
  label: string;
  admin: boolean;
  by: string;
  created?: string;
  expires: string;
}

export interface PersonRef {
  id: string;
  seq: number;
  hash: string;
}

export interface PersonView {
  person?: string;
  label: string;
  email?: string;
  address: string;
  fingerprint?: string;
  state: string;
  published?: boolean;
  agents?: AgentLink[];
  devices?: DeviceView[];
}

export interface Presence {
  text: string;
  at?: string;
}

export interface ProposalView {
  question_id: string;
  question: string;
  asker: string;
  proposal_id: string;
  proposal: string;
  confirmed_by: string;
}

export interface QuarantineItem {
  id: string;
  peer: string;
  code: string;
  reason: string;
  at: string;
}

export interface QuestionApproval {
  address?: string;
  person?: string;
  label?: string;
  status?: string;
}

export interface ReactionView {
  emoji: string;
  by: Reactor[] | null;
  mine?: boolean;
}

export interface Reactor {
  id: string;
  label: string;
  assistant?: boolean;
  host?: string;
  agent_id?: string;
  pid?: string;
}

export interface ReminderView {
  message: string;
  conv?: string;
  from: string;
  title: string;
  due: string;
  overdue: boolean;
}

export interface RemoteStorage {
  status: string;
  reason?: string;
  usage?: HubStorage;
}

export interface ReplyReceiverBindingView {
  id: string;
  conv?: string;
  request_ref: string;
  receiver: ReplyReceiverSelection;
  label: string;
  host: string;
  state: string;
  detail?: string;
  handoff_state?: string;
  handoff_label?: string;
  inputs?: ReplyReceiverInputView[];
}

export interface ReplyReceiverHost {
  address: string;
  fingerprint: string;
}

export interface ReplyReceiverInputView {
  id: string;
  state: string;
  native_state?: string;
  detail?: string;
}

export interface ReplyReceiverSelection {
  host?: ReplyReceiverHost;
  on_close?: ManagedReplyHandoff;
  kind: string;
  session_handle?: string;
  agent_id?: string;
  instructions?: string;
  mode?: string;
}

export interface ReplySessionCatalogView {
  host: string;
  local: boolean;
  sessions: ReplySessionChoice[] | null;
}

export interface ReplySessionChoice {
  handle: string;
  harness: string;
  label: string;
  active: boolean;
}

export interface Report {
  v: number;
  at: number;
  host: string;
  items: ReportItem[] | null;
  count?: number;
  deciders?: Decider[];
}

export interface ReportItem {
  id: string;
  from: string;
  key: string;
  kind: string;
  state: string;
  blocker: string;
  since: number;
  attempt: number;
  excerpt?: string;
  actionable?: boolean;
  conv?: boolean;
  proposal?: ProposalView;
  result?: DecisionResult;
}

export interface ResponderChange {
  manual: boolean;
  harness: string;
  dir: string;
}

export interface ResponderView {
  chosen: boolean;
  manual: boolean;
  harness?: string;
  dir?: string;
  timeout_seconds?: number;
  context?: string[];
  ready: boolean;
  problem?: string;
  harnesses: HarnessView[] | null;
}

export interface ReviewItem {
  id: string;
  peer: string;
  kind: string;
  why: string;
  excerpt: string;
  at: string;
  notice?: boolean;
  report?: Report;
  proposal?: ProposalView;
  reason?: string;
  conv?: string;
  agent_id?: string;
}

export interface Sent {
  lid?: string;
  id: string;
  state: string;
  path?: string;
  detail?: string;
}

export interface Skin {
  api: number;
  id: string;
  name: string;
  entry?: string;
  style?: string;
  document?: string;
  files?: string[];
  digest?: string;
}

export interface StorageAmount {
  files: number;
  bytes: number;
}

export interface StorageArea {
  directory: string;
  label: string;
  kind: string;
  status: string;
  usage?: StorageAmount;
  reason?: string;
  lifetime: string;
}

export interface StorageBucket {
  files: number;
  reserved_bytes: number;
  recorded_received_bytes: number;
}

export interface StorageSummary {
  local: LocalStorage;
  remote: RemoteStorage;
}

export interface Target {
  address: string;
  fingerprint: string;
  agent_id?: string;
  group_admission?: string;
}

export interface TaskGrantView {
  person?: string;
  label?: string;
  address: string;
  fingerprint: string;
  status: string;
}

export interface TeamChange {
  team?: string;
  op: string;
  name?: string;
  target?: string;
}

export interface TeamRef {
  id: string;
  seq: number;
  hash: string;
}

export interface TeamSnapshot {
  realm_id: string;
  sources: TeamRef[] | null;
  persons: PersonRef[] | null;
  at: number;
}

export interface TeamState {
  realm_id: string;
  id: string;
  name: string;
  seq: number;
  hash: string;
  managers: string[] | null;
  members: string[] | null;
  archived: boolean;
}

export interface TeamView {
  realm_id: string;
  id: string;
  name: string;
  seq: number;
  hash: string;
  managers: string[] | null;
  members: string[] | null;
  archived: boolean;
  member: boolean;
  manager: boolean;
  conflict: boolean;
  listed: boolean;
}

export interface TeamsView {
  realm_id?: string;
  status: string;
  current: boolean;
  reason?: string;
  at: string;
  truncated: boolean;
  teams: TeamView[] | null;
}

export interface Thread {
  id: string;
  peer: string;
  key: PeerKey;
  approved: boolean;
  permission_person?: PersonView;
  question_target?: string;
  task_target?: string;
  task_grant: string;
  messages: Message[] | null;
  topic?: ThreadSummary;
}

export interface ThreadSummary {
  conv?: string;
  id: string;
  peer: string;
  title: string;
  last: string;
  last_at: string;
  count: number;
  review: number;
  unread: number;
  running: number;
  waiting: boolean;
  key_changed: boolean;
  notices: number;
  notice_only: boolean;
  state: string;
  done_by?: string;
  conclusion?: string;
  concluded_by?: string;
  pending: boolean;
  renamed?: boolean;
  auto_title?: string;
  quiet_since: string;
  agent_id?: string;
}

export interface TopicChange {
  conv?: string;
  ids?: string[];
  counts?: Record<string, number>;
  peer: string;
  id: string;
  title?: string;
  count?: number;
}

export interface TopicEvent {
  action: string;
  seen?: string[];
}

export interface TopicPage {
  topics: ThreadSummary[] | null;
  next?: string;
  matched: number;
}

export interface TypingEntry {
  person?: string;
  address: string;
  label: string;
  expires: string;
}

export interface TypingPreferences {
  send: boolean;
  show: boolean;
}

export interface TypingResult {
  submitted: number;
  skipped: number;
  throttled: boolean;
}

export interface TypingScope {
  conv?: string;
  peer?: string;
  thread?: string;
}

export interface TypingView {
  scope: TypingScope;
  preferences: TypingPreferences;
  supported: boolean;
  current: boolean;
  entries: TypingEntry[] | null;
}

export interface WorkspaceBinding {
  id: string;
  name: string;
  endpoint: string;
  address: string;
  realm?: string;
  state: string;
  handle: string;
  hub_name?: string;
}

export interface WorkspaceInfoView {
  name: string;
  server: string;
  can_rename: boolean;
}

export interface WorkspaceJoin {
  id?: string;
  name: string;
  invite: string;
  agent: string;
}

export interface WorkspaceNameChange {
  name: string;
}

export interface WorkspaceView {
  name: string;
  server: string;
}
