"""Shared contracts for server setup subsystems."""

from __future__ import annotations

import ipaddress
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal
from urllib.parse import urlsplit

from pydantic import BaseModel, ConfigDict, Field, PrivateAttr, model_validator

from agentnet.approval.config import ApprovalOwnerOIDCConfig
from agentnet.artifacts.clamav import ScannerEndpoint
from agentnet.artifacts.scanner import ScannerTrustPolicy
from agentnet.operations.config import (
    OIDCTokenEndpointAuthMethod,
    ScannerTrustConfig,
)
from agentnet.security.signatures import P256KeyPair
from agentnet.storage.postgres import validate_ordinary_server_postgres_dsn


SETUP_ROOT = Path("/var/lib/agentnet-setup")
SYSTEMD_UNIT_ROOT = Path("/etc/systemd/system")

class ServerSetupError(RuntimeError):
    """Fail-closed setup blocker safe to show in redacted operator evidence."""

    def __init__(
        self,
        blocker: str,
        message: str,
        *,
        identity_enrolled: bool = False,
    ) -> None:
        super().__init__(message)
        self.blocker = blocker
        self.identity_enrolled = identity_enrolled
class SetupOIDCProvider(BaseModel):
    """Provider fields only; Approval trust is generated by the product setup."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    issuer: str = Field(min_length=8, max_length=512)
    client_id: str = Field(min_length=1, max_length=512)
    redirect_uri: str = Field(min_length=8, max_length=2_048)
    audience: str | None = Field(default=None, min_length=1, max_length=512)
    token_endpoint_auth_method: OIDCTokenEndpointAuthMethod = OIDCTokenEndpointAuthMethod.NONE
    client_secret_env: str | None = Field(default=None, pattern=r"^[A-Z][A-Z0-9_]{2,127}$")
    allowed_endpoint_origins: tuple[str, ...] = Field(default=(), max_length=32)
    allowed_private_endpoint_cidrs: tuple[str, ...] = Field(default=(), max_length=64)
    pinned_endpoint_addresses: tuple[str, ...] = Field(default=(), max_length=128)
    allowed_signing_algorithms: tuple[Literal["RS256", "ES256"], ...] = ("RS256",)
    pinned_jwk_thumbprints: dict[str, str] = Field(default_factory=dict)
    binding_assurance: Literal["os_bound", "hardware_bound"] = "hardware_bound"

    @model_validator(mode="after")
    def provider_contract(self) -> "SetupOIDCProvider":
        confidential = self.token_endpoint_auth_method is not OIDCTokenEndpointAuthMethod.NONE
        if confidential != (self.client_secret_env is not None):
            raise ValueError("OIDC client-secret reference policy is inconsistent")
        try:
            issuer = urlsplit(self.issuer)
            issuer_port = issuer.port
        except ValueError as exc:
            raise ValueError("OIDC issuer is invalid") from exc
        if (
            issuer.scheme != "https"
            or not issuer.hostname
            or issuer.username is not None
            or issuer.password is not None
            or issuer.query
            or issuer.fragment
            or self.issuer.endswith("/")
            or issuer_port not in {None, 443}
        ):
            raise ValueError("OIDC issuer must be one canonical HTTPS issuer")
        return self


class SetupApprover(BaseModel):
    """Non-secret approver policy applied exactly during Approval provisioning."""

    model_config = ConfigDict(extra="forbid", frozen=True)

    principal_id: str = Field(min_length=1, max_length=256)
    authority_kind: Literal["human", "guest"] = "human"
    domain_id: str = Field(pattern=r"^[a-z0-9][a-z0-9.-]{2,127}$")
    allowed_purposes: frozenset[str] = Field(min_length=1, max_length=32)
    oidc_issuer: str | None = Field(default=None, min_length=8, max_length=512)
    oidc_subject: str | None = Field(default=None, min_length=1, max_length=512)
    verified_email_alias: str | None = Field(default=None, min_length=3, max_length=320)

    @model_validator(mode="after")
    def exact_identity(self) -> "SetupApprover":
        identity_values = (self.oidc_issuer, self.oidc_subject, self.verified_email_alias)
        if any(value is not None for value in identity_values) and (
            self.oidc_issuer is None
            or (self.oidc_subject is None) == (self.verified_email_alias is None)
        ):
            raise ValueError("approver requires one exact OIDC subject or verified email alias")
        if self.verified_email_alias is not None:
            normalized = self.verified_email_alias.strip().casefold()
            try:
                normalized.encode("ascii")
            except UnicodeEncodeError as exc:
                raise ValueError("approver verified email alias must be normalized") from exc
            local, separator, domain = normalized.partition("@")
            if (
                separator != "@"
                or not local
                or not domain
                or "@" in domain
                or normalized != self.verified_email_alias
                or any(ord(character) <= 0x20 or ord(character) == 0x7F for character in normalized)
            ):
                raise ValueError("approver verified email alias must be normalized")
        if any(
            not purpose
            or len(purpose) > 256
            or purpose != purpose.strip()
            or any(ord(character) < 0x21 for character in purpose)
            for purpose in self.allowed_purposes
        ):
            raise ValueError("approver purpose is invalid")
        return self


class ServerSetupRequest(BaseModel):
    """Strict non-secret references for the fixed ordinary server-agent profile."""

    model_config = ConfigDict(extra="forbid", frozen=True, populate_by_name=True)
    _source_sha256: str = PrivateAttr(default="")

    schema_version: Literal[
        "agentnet.server-setup.request.v1",
        "agentnet.server-setup.request.v2",
    ] = Field(alias="schema")
    profile: Literal["always_on_server_agent"] = "always_on_server_agent"
    domain_id: str = Field(pattern=r"^[a-z0-9][a-z0-9.-]{2,127}$")
    service_audience: str = Field(min_length=8, max_length=512)
    runtime_instance_id: str = Field(min_length=1, max_length=128)
    core_public_origin: str = Field(min_length=8, max_length=2048)
    approval_public_origin: str = Field(min_length=8, max_length=2048)
    database_url: str = Field(min_length=16, max_length=2048)
    database_url_env: str = Field(default="AGENTNET_DATABASE_URL", pattern=r"^AGENTNET_[A-Z0-9_]{1,118}$")
    core_environment_file: Path
    approval_environment_file: Path
    oidc_provider_file: Path
    approval_owner_oidc_file: Path
    approval_approvers_file: Path
    artifact_mode: Literal["enabled", "disabled"] | None = None
    scanner_trust_file: Path | None = None
    approval_approver_principal_id: str = Field(min_length=1, max_length=256)
    approval_verifier_id: str = Field(min_length=1, max_length=128)

    @staticmethod
    def _origin(value: str, *, label: str) -> str:
        try:
            parsed = urlsplit(value)
            port = parsed.port
        except ValueError as exc:
            raise ValueError(f"{label} is invalid") from exc
        if (
            parsed.scheme != "https"
            or not parsed.hostname
            or parsed.username is not None
            or parsed.password is not None
            or parsed.path not in {"", "/"}
            or parsed.query
            or parsed.fragment
        ):
            raise ValueError(f"{label} must be one exact HTTPS origin")
        hostname = parsed.hostname.lower()
        if hostname == "localhost" or hostname.endswith((".localhost", ".local")):
            raise ValueError(f"{label} must not use a local hostname")
        try:
            literal_address = ipaddress.ip_address(hostname)
        except ValueError:
            literal_address = None
        if literal_address is not None and not literal_address.is_global:
            raise ValueError(f"{label} must not use a non-public literal address")
        host = f"[{hostname}]" if ":" in hostname else hostname
        canonical = f"https://{host}"
        if port not in {None, 443}:
            canonical += f":{port}"
        if value.rstrip("/") != canonical:
            raise ValueError(f"{label} must use canonical spelling")
        return canonical

    @model_validator(mode="after")
    def fixed_profile(self) -> "ServerSetupRequest":
        self._origin(self.core_public_origin, label="Core public origin")
        self._origin(self.approval_public_origin, label="Approval public origin")
        expected_audience = f"urn:agentnet:{self.domain_id}:corporate-api"
        if self.service_audience != expected_audience:
            raise ValueError("service_audience must be the canonical domain audience")
        try:
            validate_ordinary_server_postgres_dsn(self.database_url)
        except Exception as exc:
            raise ValueError(
                "database_url must use the fixed local PostgreSQL peer-auth contract"
            ) from exc
        fields_set = self.model_fields_set
        if self.schema_version == "agentnet.server-setup.request.v1":
            if "artifact_mode" in fields_set or self.scanner_trust_file is None:
                raise ValueError("request.v1 requires the original scanner-backed artifact profile")
        elif self.artifact_mode == "enabled":
            if "artifact_mode" not in fields_set or self.scanner_trust_file is None:
                raise ValueError("request.v2 artifact mode enabled requires scanner_trust_file")
        elif self.artifact_mode == "disabled":
            if "artifact_mode" not in fields_set or "scanner_trust_file" in fields_set:
                raise ValueError("request.v2 artifact mode disabled forbids scanner_trust_file")
        else:
            raise ValueError("request.v2 requires explicit artifact_mode")
        paths = [
            self.core_environment_file,
            self.approval_environment_file,
            self.oidc_provider_file,
            self.approval_owner_oidc_file,
            self.approval_approvers_file,
        ]
        if self.scanner_trust_file is not None:
            paths.append(self.scanner_trust_file)
        for path in paths:
            if not path.is_absolute() or ".." in path.parts:
                raise ValueError("server setup input files must use absolute canonical paths")
        if self.core_public_origin == self.approval_public_origin:
            raise ValueError("Core and Approval require distinct public HTTPS origins")
        return self

    @property
    def effective_artifact_mode(self) -> Literal["enabled", "disabled"]:
        return "enabled" if self.schema_version == "agentnet.server-setup.request.v1" else self.artifact_mode  # type: ignore[return-value]


@dataclass(frozen=True)
class SetupLayout:
    root: Path = Path("/")

    def host(self, path: Path) -> Path:
        if self.root == Path("/"):
            return path
        return self.root / path.relative_to("/")

    @property
    def lock(self) -> Path:
        return self.host(SETUP_ROOT / "setup.lock")

    def unit(self, name: str) -> Path:
        return self.host(SYSTEMD_UNIT_ROOT / name)

    @property
    def core_unit(self) -> Path:
        from .systemd import CORE_UNIT

        return self.unit(CORE_UNIT)

    @property
    def approval_unit(self) -> Path:
        from .systemd import APPROVAL_UNIT

        return self.unit(APPROVAL_UNIT)


@dataclass(frozen=True)
class SetupRuntimeIdentity:
    node_executable: Path
    node_sha256: str
    uv_executable: Path
    uv_sha256: str
    agentnet_executable: Path
    agentnet_sha256: str
    package_root: Path
    package_tree_sha256: str
    systemctl_executable: Path
    systemctl_sha256: str
    useradd_executable: Path
    useradd_sha256: str

@dataclass(frozen=True)
class ScannerSetupSpec:
    endpoint: ScannerEndpoint
    key: P256KeyPair
    key_input: bytes
    scanner_id: str
    scanner_key_epoch: int
    engine_version: str
    signature_version: str
    signature_updated_at: int
    signature_max_age_seconds: int
    rules_digest: str
    profile_digest: str
    trust_policy: ScannerTrustPolicy



@dataclass(frozen=True)
class ServerSetupPreflight:
    runtime: SetupRuntimeIdentity
    input_bundle: dict[str, bytes]
    oidc_provider: SetupOIDCProvider
    owner_oidc: ApprovalOwnerOIDCConfig
    approvers: tuple[SetupApprover, ...]
    scanner_trust: ScannerTrustConfig | None
    scanner_setup: ScannerSetupSpec | None
    core_values: dict[str, str]
    approval_values: dict[str, str]
    core_environment: dict[str, str]
    approval_environment: dict[str, str]
    request_digest: str
    legacy_request_digest: str
