package ui

import (
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"
	"time"

	"github.com/misunders2d/agentnet/internal/client"
	"github.com/misunders2d/agentnet/internal/protocol"
	"github.com/misunders2d/agentnet/internal/ui/static"
)

var updateTS = flag.Bool("update", false, "rewrite web/src/api.gen.ts")

// The page API's request and response types, as the default interface
// (web/src) reads and sends them. api.gen.ts is generated from these with
// encoding/json's rules, so the interface and the server cannot drift
// apart silently: this test fails until the file is regenerated with
//
//	go test ./internal/ui -run TestTypeScriptViewTypes -update
var tsRoots = []any{
	// responses
	Overview{}, DMThread{}, Thread{}, Presence{}, Sent{}, AgentView{}, GuestView{},
	GroupInvitationView{}, GroupChangeResult{}, ResponderView{}, AgentCatalogView{}, AgentCatalogChangeResult{},
	ReplyReceiverBindingView{}, ReplySessionCatalogView{}, NotifyView{}, DeviceLink{}, AssistantSetupView{},
	WorkspaceBinding{}, client.TeamsView{}, protocol.TeamState{}, protocol.TeamSnapshot{},
	client.TypingView{}, client.TypingResult{}, client.StorageSummary{}, static.Skin{},
	// requests
	Draft{}, DMDraft{}, Action{}, ControlAction{}, AgentInvite{}, AgentAsk{}, GuestAction{},
	GroupInviteDraft{}, GroupChange{}, DecisionAction{}, DeleteConversationAction{}, ResponderChange{},
	AgentCatalogChange{}, WorkspaceJoin{}, client.TeamChange{}, protocol.TypingScope{}, AssistantSetupRequest{},
	ReplyReceiverSelection{},
}

func TestTypeScriptViewTypes(t *testing.T) {
	got := generateTS(tsRoots)
	path := filepath.Join("web", "src", "api.gen.ts")
	if *updateTS {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(path)
	if err != nil || string(want) != got {
		t.Fatalf("%s is out of date with the page API types: go test ./internal/ui -run TestTypeScriptViewTypes -update", path)
	}
}

type tsGen struct {
	names map[reflect.Type]string
	taken map[string]reflect.Type
	decls map[string]string
	queue []reflect.Type
}

var (
	timeType      = reflect.TypeFor[time.Time]()
	rawType       = reflect.TypeFor[json.RawMessage]()
	marshalerType = reflect.TypeFor[json.Marshaler]()
)

func generateTS(roots []any) string {
	g := &tsGen{names: map[reflect.Type]string{}, taken: map[string]reflect.Type{}, decls: map[string]string{}}
	for _, r := range roots {
		g.name(reflect.TypeOf(r))
	}
	for len(g.queue) > 0 {
		t := g.queue[0]
		g.queue = g.queue[1:]
		g.decls[g.names[t]] = g.decl(t)
	}
	keys := make([]string, 0, len(g.decls))
	for k := range g.decls {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("// Code generated by internal/ui/tsgen_test.go from the page API's Go types. DO NOT EDIT.\n")
	b.WriteString("// Regenerate: go test ./internal/ui -run TestTypeScriptViewTypes -update\n")
	for _, k := range keys {
		b.WriteString("\n" + g.decls[k])
	}
	return b.String()
}

// name returns the TypeScript name for a struct type, queueing its
// declaration; two packages' types of one name get their package prefixed.
func (g *tsGen) name(t reflect.Type) string {
	if n, ok := g.names[t]; ok {
		return n
	}
	n := t.Name()
	if other, ok := g.taken[n]; ok && other != t {
		n = strings.ToUpper(t.PkgPath()[strings.LastIndex(t.PkgPath(), "/")+1:][:1]) + t.PkgPath()[strings.LastIndex(t.PkgPath(), "/")+2:] + n
	}
	g.names[t], g.taken[n] = n, t
	g.queue = append(g.queue, t)
	return n
}

func (g *tsGen) decl(t reflect.Type) string {
	var b strings.Builder
	fmt.Fprintf(&b, "export interface %s {\n", g.names[t])
	g.fields(&b, t)
	b.WriteString("}\n")
	return b.String()
}

func (g *tsGen) fields(b *strings.Builder, t reflect.Type) {
	for i := range t.NumField() {
		f := t.Field(i)
		if !f.IsExported() {
			continue
		}
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name, opts, _ := strings.Cut(tag, ",")
		if f.Anonymous && name == "" {
			ft := f.Type
			if ft.Kind() == reflect.Pointer {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct {
				g.fields(b, ft) // flattened, as encoding/json does
				continue
			}
		}
		if name == "" {
			name = f.Name
		}
		optional := strings.Contains(","+opts+",", ",omitempty,") || strings.Contains(","+opts+",", ",omitzero,")
		ts := g.ref(f.Type, !optional)
		if strings.Contains(","+opts+",", ",string,") {
			ts = "string"
		}
		q := ""
		if optional {
			q = "?"
		}
		fmt.Fprintf(b, "  %s%s: %s;\n", name, q, ts)
	}
}

// ref is the TypeScript type of a field; nullable when encoding/json may
// write null (a nil slice, map or pointer that is not omitted).
func (g *tsGen) ref(t reflect.Type, nullable bool) string {
	if t == timeType {
		return "string"
	}
	if t == rawType {
		return "unknown"
	}
	if t.Kind() != reflect.Pointer && t.Kind() != reflect.Interface && (t.Implements(marshalerType) || reflect.PointerTo(t).Implements(marshalerType)) {
		return "unknown // custom JSON"
	}
	null := func(s string) string {
		if nullable {
			return s + " | null"
		}
		return s
	}
	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Interface:
		return "unknown"
	case reflect.Pointer:
		return null(g.ref(t.Elem(), false))
	case reflect.Slice:
		if t.Elem().Kind() == reflect.Uint8 {
			return "string" // base64
		}
		return null(g.elem(t.Elem()) + "[]")
	case reflect.Array:
		return g.elem(t.Elem()) + "[]"
	case reflect.Map:
		return null("Record<string, " + g.ref(t.Elem(), false) + ">")
	case reflect.Struct:
		if t.Name() == "" { // an anonymous struct: its fields inline
			var b strings.Builder
			g.fields(&b, t)
			return "{ " + strings.Join(strings.Fields(strings.ReplaceAll(b.String(), "\n", " ")), " ") + " }"
		}
		return g.name(t)
	}
	return "unknown"
}

func (g *tsGen) elem(t reflect.Type) string {
	s := g.ref(t, false)
	if strings.Contains(s, " ") {
		return "(" + s + ")"
	}
	return s
}

// The default interface is checked in as web/build.sh made it: the bundle,
// its stylesheet, fonts and emoji data must match the digests the build
// recorded, and the source's packages must be pinned exactly.
func TestMessengerBundleMatchesBuild(t *testing.T) {
	sums, err := os.ReadFile(filepath.Join("web", "SHA256SUMS"))
	if err != nil {
		t.Fatal(err)
	}
	lines := strings.Split(strings.TrimSpace(string(sums)), "\n")
	listed := map[string]bool{}
	for _, l := range lines {
		want, name, ok := strings.Cut(l, "  ")
		if !ok {
			t.Fatalf("bad SHA256SUMS line %q", l)
		}
		listed[name] = true
		data, err := os.ReadFile(filepath.Join("static", name))
		if err != nil {
			t.Fatal(err)
		}
		if got := fmt.Sprintf("%x", sha256.Sum256(data)); got != want {
			t.Errorf("static/%s does not match web/SHA256SUMS: run web/build.sh", name)
		}
	}
	err = filepath.WalkDir(filepath.Join("static", "m"), func(path string, d os.DirEntry, err error) error {
		if err == nil && !d.IsDir() && !listed[strings.TrimPrefix(filepath.ToSlash(path), "static/")] {
			t.Errorf("%s is not produced by web/build.sh", path)
		}
		return err
	})
	if err != nil || !listed["messenger.mjs"] || !listed["messenger.css"] {
		t.Fatalf("bundle listing incomplete: %v", err)
	}
	var pkg struct{ Dependencies, DevDependencies map[string]string }
	raw, err := os.ReadFile(filepath.Join("web", "package.json"))
	if err != nil || json.Unmarshal(raw, &pkg) != nil {
		t.Fatalf("package.json: %v", err)
	}
	exact := regexp.MustCompile(`^\d+\.\d+\.\d+$`)
	for _, deps := range []map[string]string{pkg.Dependencies, pkg.DevDependencies} {
		for name, v := range deps {
			if !exact.MatchString(v) {
				t.Errorf("web/package.json: %s %q is not an exact version", name, v)
			}
		}
	}
}
